using System.Text;
using MediatR;
using Microsoft.Extensions.Logging;
using Shipra.Backend.API.Application.Common;
using Shipra.Backend.API.Application.DTOs;
using Shipra.Backend.API.Core.Interfaces;

namespace Shipra.Backend.API.Application.Features.ProductFeatures.Query.GetUniqueAutoGeneratedSku;
public class GetUniqueAutoGeneratedSkuQuery : IRequest<ServiceResultDTO>
{
}
public class GetUniqueAutoGeneratedSkuQueryHandler : RequestHandlerBase<GetUniqueAutoGeneratedSkuQuery, ServiceResultDTO>
{
  private readonly IProductRepository _productRepository;

  public GetUniqueAutoGeneratedSkuQueryHandler(IProductRepository productRepository, IServiceProvider serviceProvider, ILogger<GetUniqueAutoGeneratedSkuQueryHandler> logger) : base(serviceProvider, logger)
  {
    _productRepository = productRepository;
  }

  protected override async Task<ServiceResultDTO> HandleRequest(GetUniqueAutoGeneratedSkuQuery request, CancellationToken cancellationToken)
  {
    ServiceResultDTO serviceResult = new ServiceResultDTO();
    try
    {
      Random random = new Random();
      int randomNumber = random.Next(1000000);
      const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
      StringBuilder randomWord = new StringBuilder();
      for (int i = 0; i < 4; i++)
      {
        randomWord.Append(chars[random.Next(chars.Length)]);
      }
      string generatedSku = $"{randomWord!.ToString() + randomNumber}";

      var result = await _productRepository.CheckAutogeneratedUniqueProductSKU(_currentUser.ClientIdStr!, generatedSku);
      if (result)
      {
        serviceResult = new ServiceResultDTO(new { Message = "Sku already exists !" });
      }
      else
      {
        serviceResult = new ServiceResultDTO(new { sku = generatedSku });
      }
      return serviceResult;
    }
    catch (Exception ex)
    {
      serviceResult.CreateErrorResponse(ex);
      throw;
    }
  }
}
