namespace Shipra.Backend.API.Core.Enum;
public enum EnumCarrierTrackingStatus
{
  OrderPlaced = 1, 
  InOperation = 2,
  AssignInHouse = 3,
  UnAssignfromcarrier = 4,
  OutForDelivery = 5,
  Delivered = 6,
  Refunded = 7,
  Exchanged = 8,
  PendingForReturn = 9,
  Returned = 10,
  AssignedTocarrier = 11,  
  OutOfStock = 12,
  OnHold = 13,
  MobileSwitchedOff = 14,
  WrongItem = 15, 
  AssignedTocarrierFaild = 16,
  Cancelled = 17, 
  HandOverToCarrier = 18,
  MobileNotAnswered = 19,
  Delayed = 20,
  WrongAmmount = 21,
  InTransit = 22,
  Lost = 23,
  Damage = 24,
  Schedulefortomorrow = 25 ,
  ReturnToOrigin = 26,
  LocationChanged = 27,
  HalfDelivered = 28,
}
