// import DeleteIcon from "@mui/icons-material/Delete";
// import EditIcon from "@mui/icons-material/Edit";
// import KeyboardArrowDownIcon from "@mui/icons-material/KeyboardArrowDown";
// import {
//   Autocomplete,
//   Avatar,
//   Box,
//   Button,
//   CardHeader,
//   Checkbox,
//   Chip,
//   CircularProgress,
//   Dialog,
//   DialogActions,
//   DialogContent,
//   DialogContentText,
//   FormControlLabel,
//   FormGroup,
//   FormLabel,
//   Grid,
//   IconButton,
//   InputLabel,
//   MenuItem,
//   Slide,
//   Stack,
//   TextField,
//   Typography,
// } from "@mui/material";
// import Divider from "@mui/material/Divider";
// import Menu from "@mui/material/Menu";
// import Paper from "@mui/material/Paper";
// import Table from "@mui/material/Table";
// import TableBody from "@mui/material/TableBody";
// import TableCell, { tableCellClasses } from "@mui/material/TableCell";
// import TableContainer from "@mui/material/TableContainer";
// import TableHead from "@mui/material/TableHead";
// import TableRow from "@mui/material/TableRow";
// import TableSortLabel from "@mui/material/TableSortLabel";
// import Toolbar from "@mui/material/Toolbar";
// import { alpha, styled } from "@mui/material/styles";
// import PropTypes from "prop-types";
// import React, { Fragment, useEffect, useState } from "react";
// import { Controller, useForm, useWatch } from "react-hook-form";
// import { useSelector } from "react-redux";
// import { useNavigate } from "react-router-dom";
// import {
//   CheckUniqueProductStockSku,
//   CreateProduct,
//   CreateProductCategory,
//   GetAllProductCategoryLookup,
//   GetAllProductOptionLookup,
//   GetAllStationLookup,
//   GetAllStores,
//   GetStoresForSelection,
// } from "../../../../api/AxiosInterceptors";
// import ImageIcon from "../../../../assets/images/uploadImage.png";
// import { styleSheet } from "../../../../assets/styles/style";
// import DragDropAllFiles from "../../../../components/dragAndDrop/allImages";
// import DragDropFile from "../../../../components/dragAndDrop/featureImage";
// import {
//   errorNotification,
//   successNotification,
// } from "../../../../utilities/toast";
// import { GetUniqueAutogeneratedSku } from "../../../../api/AxiosInterceptors";
// import { EnumAllProductOption } from "../../../../utilities/enum";
// import { ActionButtonDelete } from "../../../../utilities/helpers/Helpers";
// import {
//   getAllStationLookupFunc,
//   getAllStoresForSelectionFunc,
// } from "../../../../apiCallingFunction";
function gData() {
  const groupedData = products.reduce((acc, item) => {
    const { SKU } = item;
    const existingItem = acc.find((group) => group.SKU === SKU);

    if (existingItem) {
      existingItem.variants.push(item.variantOption);
      existingItem.stationIds.push(item.stationIds);
      existingItem.quantities += item.quantities;
    } else {
      acc.push({
        SKU,
        prices: item.prices,
        quantities: item.quantities,
        lowQuantityLimit: item.lowQuantityLimit,
        variants: [item.variantOption],
        stationIds: [item.stationIds],
        SKUChecked: item.SKUChecked,
        isAddedStationQty: item.isAddedStationQty,
      });
    }
    return acc;
  });
}
// const StyledTableCell = styled(TableCell)(({ theme }) => ({
//   [`&.${tableCellClasses.head}`]: {
//     backgroundColor: theme.palette.common.black,
//     color: theme.palette.common.white,
//   },
//   [`&.${tableCellClasses.body}`]: {
//     fontSize: 14,
//   },
// }));

// const StyledTableRow = styled(TableRow)(({ theme }) => ({
//   "&:nth-of-type(odd)": {
//     backgroundColor: theme.palette.action.hover,
//   },
//   "&:last-child td, &:last-child th": {
//     border: 0,
//   },
// }));

// const StyledMenu = styled((props) => (
//   <Menu
//     elevation={0}
//     anchorOrigin={{
//       vertical: "bottom",
//       horizontal: "right",
//     }}
//     transformOrigin={{
//       vertical: "top",
//       horizontal: "right",
//     }}
//     {...props}
//   />
// ))(({ theme }) => ({
//   "& .MuiPaper-root": {
//     borderRadius: 6,
//     marginTop: theme.spacing(1),
//     minWidth: 180,
//     color:
//       theme.palette.mode === "light"
//         ? "rgb(55, 65, 81)"
//         : theme.palette.grey[300],
//     boxShadow:
//       "rgb(255, 255, 255) 0px 0px 0px 0px, rgba(0, 0, 0, 0.05) 0px 0px 0px 1px, rgba(0, 0, 0, 0.1) 0px 10px 15px -3px, rgba(0, 0, 0, 0.05) 0px 4px 6px -2px",
//     "& .MuiMenu-list": {
//       padding: "4px 0",
//     },
//     "& .MuiMenuItem-root": {
//       "& .MuiSvgIcon-root": {
//         fontSize: 18,
//         color: theme.palette.text.secondary,
//         marginRight: theme.spacing(1.5),
//       },
//       "&:active": {
//         backgroundColor: alpha(
//           theme.palette.primary.main,
//           theme.palette.action.selectedOpacity
//         ),
//       },
//     },
//   },
// }));

// function EnhancedTableToolbar(props) {
//   const LanguageReducer = useSelector((state) => state.LanguageReducer);
//   const {
//     numSelected,
//     handleOpenPrices,
//     handleOpenQuantities,
//     handleOpenSKU,
//     handleCloseQuantities,
//     handleCloseSKU,
//     handleClosePrices,
//   } = props;
//   const [anchorEl, setAnchorEl] = React.useState(null);

//   const open = Boolean(anchorEl);
//   const handleClick = (event) => {
//     setAnchorEl(event.currentTarget);
//   };
//   const handleClose = () => {
//     setAnchorEl(null);
//   };

//   return (
//     <Toolbar
//       sx={{
//         pl: { sm: 2 },
//         pr: { xs: 1, sm: 1 },
//         ...(numSelected > 0 && {
//           bgcolor: (theme) =>
//             alpha(
//               theme.palette.primary.main,
//               theme.palette.action.activatedOpacity
//             ),
//         }),
//       }}
//     >
//       {numSelected > 0 ? (
//         <Typography
//           sx={{ flex: "1 1 100%" }}
//           color="inherit"
//           variant="subtitle1"
//           component="div"
//         >
//           {numSelected} {LanguageReducer?.languageType?.SELECTED_TEXT}
//         </Typography>
//       ) : (
//         <Typography
//           sx={{ flex: "1 1 100%" }}
//           color="inherit"
//           variant="subtitle1"
//           component="div"
//         >
//           {0} {LanguageReducer?.languageType?.SELECTED_TEXT}
//         </Typography>
//       )}

//       {numSelected > 0 ? (
//         <div>
//           <Button
//             id="demo-customized-button"
//             aria-controls={open ? "demo-customized-menu" : undefined}
//             aria-haspopup="true"
//             aria-expanded={open ? "true" : undefined}
//             variant="contained"
//             disableElevation
//             onClick={handleClick}
//             endIcon={<KeyboardArrowDownIcon />}
//             sx={{
//               background:
//                 "var(--primary-color)",
//               fontFamily: "'Lato Medium', 'Inter Medium', 'Arial' !important",
//               textTransform: "capitalize  !important",
//             }}
//           >
//             {LanguageReducer?.languageType?.EDIT_TEXT}
//           </Button>
//           <StyledMenu
//             id="demo-customized-menu"
//             MenuListProps={{
//               "aria-labelledby": "demo-customized-button",
//             }}
//             anchorEl={anchorEl}
//             open={open}
//             onClose={handleClose}
//           >
//             <MenuItem
//               onClick={() => {
//                 handleOpenPrices();
//                 handleCloseSKU();
//                 handleCloseQuantities();
//                 setAnchorEl(null);
//               }}
//               disableRipple
//             >
//               <EditIcon />
//               {LanguageReducer?.languageType?.EDIT_PRICES_TEXT}
//             </MenuItem>
//             <MenuItem
//               onClick={() => {
//                 handleOpenSKU();
//                 handleClosePrices();
//                 handleCloseQuantities();
//                 setAnchorEl(null);
//               }}
//               disableRipple
//             >
//               <EditIcon />
//               {LanguageReducer?.languageType?.EDIT_SKU_TEXT}
//             </MenuItem>
//             <MenuItem
//               onClick={() => {
//                 handleOpenQuantities();
//                 handleCloseSKU();
//                 handleClosePrices();
//                 setAnchorEl(null);
//               }}
//               disableRipple
//             >
//               <EditIcon />
//               {LanguageReducer?.languageType?.EDIT_QUNATITIES_TEXT}
//             </MenuItem>
//           </StyledMenu>
//         </div>
//       ) : null}
//     </Toolbar>
//   );
// }
// EnhancedTableToolbar.propTypes = {
//   numSelected: PropTypes.number.isRequired,
// };

// const Transition = React.forwardRef(function Transition(props, ref) {
//   return <Slide direction="up" ref={ref} {...props} />;
// });

// function Products(props) {
//   let navigate = useNavigate();
//   const LanguageReducer = useSelector((state) => state.LanguageReducer);
//   const [stores, setStores] = useState([]);
//   const [open, setOpen] = useState(false);
//   const [openSKU, setOpenSKU] = useState(false);
//   const [openPrices, setOpenPrices] = useState(false);
//   const [openQuantities, setOpenQuantities] = useState(false);
//   const [inputFields, setInputFields] = useState([
//     { selectedOption: "", options: [] },
//   ]);
//   const [categoryName, setCategoryName] = useState("");
//   const [stationValues, setStationValues] = useState([]);
//   const [productCategories, setProductCategories] = useState([]);
//   const [productStations, setProductStations] = useState([]);
//   const [allProductOptions, setAllProductOptions] = useState([]);
//   const [optionsCheckbox, setOptionsCheckbox] = useState(false);
//   const [trackInventoryCheckbox, setTrackInventoryCheckbox] = useState(true);
//   const [autoGenerateSku, setAutoGenerateSku] = useState(true);
//   const [selected, setSelected] = useState([]);
//   const [productFile, setProductFile] = useState();
//   const [isLoading, setIsLoading] = useState(false);
//   const [isLowerPrice, setIsLowerPrice] = useState(false);
//   const [optionValuePlaceHolder, setOptionValuePlaceHolder] = useState();

//   const [combinations, setCombinations] = useState([]);
//   const [tempCombinations, setTempCombinations] = useState([]);
//   const {
//     register,
//     handleSubmit,
//     formState: { errors },
//     reset,
//     getValues,
//     setValue,
//     watch,
//     control,
//   } = useForm({
//     defaultValues: {
//       productCategoryId: productCategories && productCategories[0],
//     },
//   });
//   useWatch({ name: "SKU", control });
//   useWatch({ name: "store", control });
//   useWatch({ name: "productCategoryId", control });

//   const handleFocus = (event) => event.target.select();
//   const [autocompleteInput, setAutocompleteInput] = useState("");

//   const handleKeyDown = (event, index) => {
//     if (event.key === "Tab" && event.target.value.trim() !== "") {
//       event.preventDefault(); // Prevent the default tab behavior.
//       const newOption = event.target.value.trim();
//       if (!inputFields[index].options.includes(newOption)) {
//         const updatedInputFields = [...inputFields];
//         updatedInputFields[index].options.push(newOption);
//         setInputFields(updatedInputFields);
//         setSelected([]);
//       }
//     }
//   };
//   const handleClose = () => {
//     setOpen(false);
//   };

//   const handleOpen = () => {
//     setOpen(true);
//   };

//   const handleClosePrices = () => {
//     setOpenPrices(false);
//   };

//   const handleOpenPrices = () => {
//     setOpenPrices(true);
//   };

//   const handleCloseSKU = () => {
//     setOpenSKU(false);
//   };

//   const handleOpenSKU = () => {
//     setOpenSKU(true);
//   };

//   const handleCloseQuantities = () => {
//     setOpenQuantities(false);
//   };

//   const handleOpenQuantities = () => {
//     setOpenQuantities(true);
//   };

//   const handleSelectAllClick = (event) => {
//     if (event.target.checked) {
//       const newSelected = combinations.map((n, indx) => indx);
//       setSelected(newSelected);
//       return;
//     }
//     setSelected([]);
//   };

//   const handleClick = (event, name) => {
//     const selectedIndex = selected.indexOf(name);
//     let newSelected = [];

//     if (selectedIndex === -1) {
//       newSelected = newSelected.concat(selected, name);
//     } else if (selectedIndex === 0) {
//       newSelected = newSelected.concat(selected.slice(1));
//     } else if (selectedIndex === selected.length - 1) {
//       newSelected = newSelected.concat(selected.slice(0, -1));
//     } else if (selectedIndex > 0) {
//       newSelected = newSelected.concat(
//         selected.slice(0, selectedIndex),
//         selected.slice(selectedIndex + 1)
//       );
//     }
//     setSelected(newSelected);
//   };

//   const isSelected = (name) => selected.indexOf(name) !== -1;
//   const headCells = [
//     {
//       id: "name",
//       numeric: false,
//       disablePadding: true,
//       label: `${LanguageReducer?.languageType?.SHOWING_TEXT} ${combinations.length} ${LanguageReducer?.languageType?.VARIANTS_TEXT} `,
//     },
//     {},
//   ];

//   function generateCombinations(optionsArray) {
//     const combinations = [[]]; // Start with an empty combination

//     optionsArray.forEach((optionsObj) => {
//       const newCombinations = [];

//       optionsObj.options.forEach((option) => {
//         combinations.forEach((combination) => {
//           newCombinations.push([...combination, option]);
//         });
//       });
//       combinations.push(...newCombinations);
//     });

//     return combinations.slice(1); // Exclude the empty combination
//   }

//   const optionsCombinations = (optionsArray) => {
//     const filteredOptionsArray = optionsArray.filter((optionArray) => {
//       return optionArray.options.length !== 0;
//     });
//     const combinations = generateCombinations(optionsArray);
//     const filteredArray = combinations.filter((combination) => {
//       return combination.length == filteredOptionsArray.length;
//     });
//     let structureArray = [];
//     for (let index = 0; index < filteredArray.length; index++) {
//       structureArray[index] = {
//         SKU: getValues("SKU") + "-" + index,
//         prices: getValues("price") ? getValues("price") : 0,
//         quantities: 0,
//         lowQuantityLimit: 0,
//         variants: filteredArray[index],
//         stationIds: productStations,
//         SKUChecked: false,
//       };
//     }
//     setTempCombinations(structureArray);
//     setCombinations(structureArray);
//   };
//   let getUniqueAutogeneratedSku = async () => {
//     let res = await GetUniqueAutogeneratedSku();
//     if (res.data.isSuccess) {
//       setValue("SKU", res.data.result.sku);
//     } else {
//       setValue("SKU", "");
//     }
//   };
//   useEffect(() => {
//     if (autoGenerateSku) {
//       getUniqueAutogeneratedSku();
//     } else {
//       setValue("SKU", "");
//     }
//   }, [autoGenerateSku]);
//   const handleAutoGenerate = (e) => {
//     setAutoGenerateSku(!autoGenerateSku);
//   };
//   useEffect(() => {
//     optionsCombinations(inputFields);
//   }, [inputFields]);

//   const addInputField = () => {
//     setInputFields([
//       ...inputFields,
//       {
//         selectedOption: "",
//         options: [],
//       },
//     ]);
//   };

//   const removeInputFields = (index) => {
//     const rows = [...inputFields];
//     rows.splice(index, 1);
//     setInputFields(rows);
//   };
//   const handlePlaceHolderForOption = (value, index) => {
//     console.log(value, index);

//     if (value == EnumAllProductOption.Size) {
//       setOptionValuePlaceHolder((prevStates) => ({
//         ...prevStates,
//         [index]: "Small",
//       }));
//     } else if (value == EnumAllProductOption.Company) {
//       setOptionValuePlaceHolder((prevStates) => ({
//         ...prevStates,
//         [index]: "Shipra",
//       }));
//     } else if (value == EnumAllProductOption.Color) {
//       setOptionValuePlaceHolder((prevStates) => ({
//         ...prevStates,
//         [index]: "Purple",
//       }));
//     } else if (value == EnumAllProductOption.Model) {
//       setOptionValuePlaceHolder((prevStates) => ({
//         ...prevStates,
//         [index]: "2023",
//       }));
//     } else {
//       setOptionValuePlaceHolder((prevStates) => ({
//         ...prevStates,
//         [index]: "Select option",
//       }));
//     }
//   };
//   const handleChange = (index, evnt) => {
//     console.log("row index" + index);
//     const { name, value } = evnt.target;
//     handlePlaceHolderForOption(value, index);
//     const list = [...inputFields];
//     list[index]["selectedOption"] = value;
//     setInputFields(list);
//     let priceArr = [...combinations];
//     priceArr[index] = {
//       ...priceArr[index],
//       optionId: value,
//     };
//     setCombinations(priceArr);
//     setTempCombinations(priceArr);
//   };
//   let getAllStores = async () => {
//     let data = await getAllStoresForSelectionFunc();
//     if (data?.length > 0) {
//       setStores(data);
//     }
//   };
//   let getAllProductCategoryLookup = async () => {
//     let res = await GetAllProductCategoryLookup();
//     console.log("getAllProductCategoryLookup", res.data);
//     if (res.data.result !== null) setProductCategories(res.data.result);
//   };
//   let getAllStationLookup = async () => {
//     let data = await getAllStationLookupFunc();
//     if (data.length > 0) {
//       if (data?.find((x) => x.productStationId == 0)) {
//         data.shift();
//       }
//       const updatedData = data.map((item) => ({
//         ...item,
//         qty: 0, // You can set the initial value of qty as needed
//         lowQtyLimit: 0, // You can set the initial value of lowQtyLimit as needed
//       }));

//       setProductStations(updatedData);
//     }
//   };
//   let getAllProductOptionLookup = async () => {
//     let res = await GetAllProductOptionLookup({});
//     console.log("getAllProductOptionLookup", res.data);
//     if (res.data.result !== null) setAllProductOptions(res.data.result);
//   };

//   useEffect(() => {
//     getAllStores();
//     getAllProductCategoryLookup();
//     getAllStationLookup();
//     getAllProductOptionLookup();
//   }, []);

//   const createCategory = () => {
//     if (categoryName == "") {
//       errorNotification(
//         LanguageReducer?.languageType?.CATEGORY_NAME_CANNOT_BE_EMPTY_TOAST
//       );
//       return;
//     }
//     CreateProductCategory({ categoryName: categoryName })
//       .then((res) => {
//         console.log("res:", res);
//         if (!res?.data?.isSuccess) {
//           errorNotification(
//             LanguageReducer?.languageType?.UNABLE_TO_CREATE_CATEGORY_TOAST
//           );
//           errorNotification(res?.data?.customErrorMessage);
//         } else {
//           successNotification(
//             LanguageReducer?.languageType?.CATEGORY_CREATED_SUCCESSFULLY_TOAST
//           );
//           handleClose();
//         }
//         getAllProductCategoryLookup();
//       })
//       .catch((e) => {
//         console.log("e", e);
//         errorNotification(
//           LanguageReducer?.languageType?.UNABLE_TO_CREATE_CATEGORY_TOAST
//         );
//       });
//   };

//   const createProduct = async (data) => {
//     if (!productFile) {
//       errorNotification(
//         LanguageReducer?.languageType?.PLEASE_UPLOAD_FEATURE_IMAGE_TOAST
//       );
//       return;
//     }
//     let res = await CheckUniqueProductStockSku(data.SKU);
//     if (res.data.result.isExist) {
//       errorNotification(
//         LanguageReducer?.languageType?.SKU_NOT_AVAILBE_EMPTY_TOAST
//       );
//       return;
//     }
//     let productStocks = [{}];
//     let count = 0;
//     console.log("stationValues", stationValues);
//     console.log("combinations", combinations);

//     let errForStations = [];

//     if (!optionsCheckbox) {
//       for (let index = 0; index < stationValues.length; index++) {
//         if (stationValues[index]) {
//           productStocks[count] = {
//             Sku: data.SKU,
//             price: data.price,
//             QuantityAvailable: stationValues[index].quantityAvailable,
//             LowQuantityLimit: stationValues[index].lowQuantityLimit,
//             ProductStationId: stationValues[index].productStationId,
//             VarientOption: "1",
//           };
//           count++;
//         }
//       }
//     } else {
//       for (let index = 0; index < combinations.length; index++) {
//         if (combinations[index]) {
//           if (combinations[index].stationIds.length > 0) {
//             for (let j = 0; j < combinations[index].stationIds.length; j++) {
//               productStocks[count] = {
//                 Sku:
//                   combinations[index].SKU == ""
//                     ? data.SKU + "-" + index
//                     : combinations[index].SKU,
//                 price: combinations[index].prices,
//                 QuantityAvailable: combinations[index].quantities,
//                 LowQuantityLimit: combinations[index].lowQuantityLimit,
//                 ProductStationId: combinations[index].stationIds[j],
//                 VarientOption: "1",
//               };
//               count++;
//             }
//           } else {
//             errForStations.push({ index: index, sku: combinations[index].SKU });
//           }
//         }
//       }
//     }
//     if (errForStations.length > 0 && optionsCheckbox) {
//       errForStations.forEach((element) => {
//         errorNotification(
//           "Please add quanity and choose station against " +
//             element.sku +
//             " at row " +
//             element.index +
//             1
//         );
//         return false;
//       });
//     } else {
//       setIsLoading(true);

//       let productOptions = [{}];
//       let productOptionCount = 0;
//       for (let index = 0; index < inputFields.length; index++) {
//         if (inputFields[index]) {
//           for (
//             let jindex = 0;
//             jindex < inputFields[index].options.length;
//             jindex++
//           ) {
//             productOptions[productOptionCount] = {
//               OptionId: inputFields[index].selectedOption,
//               OptionValue: inputFields[index].options[jindex],
//             };
//             productOptionCount++;
//           }
//         }
//       }
//       const params = {
//         sku: data.SKU,
//         productName: data.productName,
//         price: data.price,
//         purchasePrice: data.purchasePrice,
//         description: data.description,
//         productCategoryId: data.productCategoryId.productCategoryId,
//         featureImage: productFile,
//         weight: data.weight,
//         haveOptions: optionsCheckbox,
//         storeId: data.store.storeId,
//         trackInventory: trackInventoryCheckbox,
//         productOptions: optionsCheckbox == false ? [] : productOptions,
//         productStocks: productStocks,
//       };
//       console.log("params", params);
//       CreateProduct(params)
//         .then((res) => {
//           console.log("res:::", res);
//           if (!res?.data?.isSuccess) {
//             errorNotification(
//               LanguageReducer?.languageType?.UNABLE_TO_CREATE_PRODUCT_TOAST
//             );
//             errorNotification(res?.data?.customErrorMessage);
//             setIsLoading(false);
//           } else {
//             successNotification(
//               LanguageReducer?.languageType?.PRODUCT_CREATED_SUCCESSFULLY_TOAST
//             );
//             setIsLoading(false);
//             navigate("/products");
//           }
//         })
//         .catch((e) => {
//           console.log("e", e);
//           setIsLoading(false);
//           errorNotification(
//             LanguageReducer?.languageType?.UNABLE_TO_CREATE_PRODUCT_TOAST
//           );
//         });
//     }
//   };
//   useEffect(() => {
//     let sp = getValues("price");
//     let pp = getValues("purchasePrice");
//     if (parseInt(sp) && parseInt(pp)) {
//       if (parseInt(sp) < parseInt(pp)) {
//         setIsLowerPrice(true);
//       } else {
//         setIsLowerPrice(false);
//       }
//     } else {
//       setIsLowerPrice(false);
//     }
//   }, [watch("purchasePrice"), watch("price")]);

//   useEffect(() => {
//     console.log(combinations);
//     if (combinations.length > 0) {
//       const updatedArr = combinations.map((item, idx) => {
//         return {
//           ...item,
//           SKU: getValues("SKU") + "-" + idx,
//           prices: getValues("price"),
//         };
//       });
//       setCombinations(updatedArr);
//     } else {
//     }
//   }, [watch("SKU"), watch("price")]);
//   const [defaultStationQts, setDefaultStationQts] = useState({
//     id: 0,
//     qty: 0,
//     lowLimitQty: 0,
//   });
//   //#region

//   const getValueFromRow = (items, index) => {
//     {
//       let val = productStations.map((ps, index) => {
//         // let stationArr = [...tempCombinations];
//         // let stationIds = stationArr[items].stationIds;
//         // if (
//         //   !stationArr[items].stationIds.find((id) => id == ps.productStationId)
//         // )
//         //   stationIds.push({ id: ps.productStationId, qty: 0 });
//         // stationArr[items] = {
//         //   ...stationArr[items],
//         //   stationIds: stationIds,
//         // };
//         // setTempCombinations(stationArr);

//         return (
//           <>
//             <StyledTableRow key={index}>
//               <StyledTableCell align="left" component="th" scope="row">
//                 {combinations[items]?.variants?.map((option, optionIndex) =>
//                   optionIndex == combinations[items]?.variants?.length - 1
//                     ? `${option}`
//                     : `${option}/`
//                 )}
//               </StyledTableCell>
//               <StyledTableCell align="center" component="th" scope="row">
//                 {ps.sname}
//               </StyledTableCell>
//               {/* <StyledTableCell align="center">
//                 <TextField
//                   fullWidth
//                   label={"Select Station"}
//                   onChange={(e) => {
//                     let stationArr = [...tempCombinations];
//                     let stationIds = stationArr[items].stationIds;
//                     if (
//                       !stationArr[items].stationIds.find(
//                         (id) => id == e.target.value
//                       )
//                     )
//                       stationIds.push(e.target.value);
//                     stationArr[items] = {
//                       ...stationArr[items],
//                       stationIds: stationIds,
//                     };
//                     setTempCombinations(stationArr);
//                   }}
//                   sx={{
//                     width: 220,
//                   }}
//                   defaultValue=""
//                   select
//                   size="small"
//                   variant="outlined"
//                 >
//                   {productStations.map((productStation) => {
//                     return (
//                       <MenuItem
//                         key={productStation.productStationId}
//                         value={productStation.productStationId}
//                       >
//                         {productStation.sname}
//                       </MenuItem>
//                     );
//                   })}
//                 </TextField>
//               </StyledTableCell> */}

//               <StyledTableCell align="">
//                 <TextField
//                   fullWidth
//                   placeholder="Quantity"
//                   label="Quantity"
//                   onChange={(e) => {
//                     handleStationQuantity(e, items, ps?.productStationId);
//                   }}
//                   value={
//                     tempCombinations[items]?.stationIds?.find(
//                       (x) => x.productStationId == ps?.productStationId
//                     )?.qty
//                   }
//                   sx={{
//                     width: 150,
//                   }}
//                   onFocus={handleFocus}
//                   variant="outlined"
//                   size="small"
//                 ></TextField>
//               </StyledTableCell>
//               <StyledTableCell align="">
//                 <TextField
//                   placeholder="Low Quantity Limit"
//                   label="Low Quantity Limit"
//                   onChange={(e) => {
//                     handleStationLowQuantity(
//                       e,
//                       items,
//                       ps?.productStationId,
//                       true
//                     );
//                   }}
//                   value={
//                     tempCombinations[items]?.stationIds?.find(
//                       (x) => x.productStationId == ps?.productStationId
//                     )?.lowQtyLimit
//                   }
//                   sx={{
//                     width: 150,
//                   }}
//                   fullWidth
//                   onFocus={handleFocus}
//                   variant="outlined"
//                   size="small"
//                 ></TextField>
//               </StyledTableCell>
//             </StyledTableRow>
//           </>
//         );
//       });
//       return val;
//     }
//   };

//   const handleStationQuantity = (e, items, stationId) => {
//     let quantityArr = [...tempCombinations];
//     const updatedStations = quantityArr[items]?.stationIds.map((station) => {
//       if (station.productStationId == stationId) {
//         let uData = {
//           ...station,
//           qty: eval(e.target.value) ? eval(e.target.value) : 0,
//         };
//         return uData;
//       }
//       return station;
//     });
//     //sum of all station qty
//     const sumOfQty = updatedStations?.reduce((accumulator, currentItem) => {
//       return accumulator + currentItem.qty;
//     }, 0);
//     quantityArr[items] = {
//       ...quantityArr[items],
//       quantities: sumOfQty,
//       stationIds: updatedStations,
//     };

//     setTempCombinations(quantityArr);
//   };
//   const handleStationLowQuantity = (e, items, stationId) => {
//     let quantityArr = [...tempCombinations];
//     const updatedStations = quantityArr[items]?.stationIds.map((station) => {
//       if (station.productStationId == stationId) {
//         let uData = {
//           ...station,
//           lowQtyLimit: eval(e.target.value) ? eval(e.target.value) : 0,
//         };
//         return uData;
//       }
//       return station;
//     });
//     //sum of all station qty
//     const sumOfQty = updatedStations?.reduce((accumulator, currentItem) => {
//       return accumulator + currentItem.lowQtyLimit;
//     }, 0);
//     quantityArr[items] = {
//       ...quantityArr[items],
//       lowQuantityLimit: sumOfQty,
//       stationIds: updatedStations,
//     };

//     setTempCombinations(quantityArr);
//   };
//   //#endregion

//   return (
//     <Box sx={styleSheet.pageRoot}>
//       {/* <Container maxWidth="xl" fixed sx={{ paddingLeft: "0px" }}> */}
//       <div style={{ padding: "10px" }}>
//         {" "}
//         <br />
//         <form onSubmit={handleSubmit(createProduct)}>
//           <Grid container spacing={8}>
//             <Grid item md={6} xs={12}>
//               <Typography sx={styleSheet.productsHeading} variant="h5">
//                 {LanguageReducer?.languageType?.PRODUCT_DETAIL_TEXT}
//               </Typography>
//               <Grid item xs={12}>
//               </Grid>{" "}
//               <Grid item sx={12}>
//                 <InputLabel required sx={styleSheet.inputLabelAddProduct}>
//                   {LanguageReducer?.languageType?.ENTER_TITLE_TEXT}
//                 </InputLabel>
//                 <TextField
//                   type="text"
//                   size="small"
//                   id="productName"
//                   name="productName"
//                   onFocus={handleFocus}
//                   fullWidth
//                   variant="outlined"
//                   {...register("productName", {
//                     required: {
//                       value: true,
//                       message:
//                         LanguageReducer?.languageType?.FIELD_REQUIRED_TEXT,
//                     },
//                     pattern: {
//                       value: /^(?!\s*$).+/,
//                       message:
//                         LanguageReducer?.languageType
//                           ?.INPUT_SHOULD_NOT_BE_ONLY_SPACES,
//                     },
//                   })}
//                   error={Boolean(errors.productName)} // set error prop
//                   helperText={errors.productName?.message}
//                   placeholder="Title"
//                 ></TextField>
//               </Grid>
//               <Grid item sx={12}>
//                 <InputLabel required sx={styleSheet.inputLabelAddProduct}>
//                   {LanguageReducer?.languageType?.ENTER_DESCRIPTION_TEXT}
//                 </InputLabel>
//                 <TextField
//                   placeholder="Description"
//                   onFocus={handleFocus}
//                   size="small"
//                   multiline
//                   fullWidth
//                   rows={3}
//                   variant="outlined"
//                   id="description"
//                   name="description"
//                   {...register("description", {
//                     required: {
//                       value: true,
//                       message:
//                         LanguageReducer?.languageType?.FIELD_REQUIRED_TEXT,
//                     },
//                     pattern: {
//                       value: /^(?!\s*$).+/,
//                       message:
//                         LanguageReducer?.languageType
//                           ?.INPUT_SHOULD_NOT_BE_ONLY_SPACES,
//                     },
//                   })}
//                   error={Boolean(errors.description)} // set error prop
//                   helperText={errors.description?.message}
//                 />
//               </Grid>
//             </Grid>
//             <Grid item md={6} xs={12}>
//               <Typography
//                 sx={{ ...styleSheet.productsHeading, marginBottom: "60px" }}
//                 variant="h5"
//               >
//                 {"Feature Image"}
//               </Typography>
//               <DragDropFile setProductFile={setProductFile} />

//               {/* <DragDropAllFiles /> */}
//             </Grid>
//             <Grid style={{ paddingTop: "0px" }} item md={6} xs={12}>
//               <Grid container spacing={3}>
//                 <Grid item md={6} xs={12}>
//                   <InputLabel required sx={styleSheet.inputLabelAddProduct}>
//                     {LanguageReducer?.languageType?.SELECT_CATEGORY_TEXT}
//                   </InputLabel>
//                   <Grid container spacing={0}>
//                     <Grid item xs={11}>
//                       <Controller
//                         name="productCategoryId"
//                         control={control}
//                         defaultValue={productCategories && productCategories[0]}
//                         rules={{
//                           required: {
//                             value: true,
//                             message:
//                               LanguageReducer?.languageType
//                                 ?.FIELD_REQUIRED_TEXT,
//                           },
//                           validate: {
//                             positive: (v) => parseInt(v.productCategoryId) > 0,
//                           },
//                         }}
//                         render={({ field }) => (
//                           <Autocomplete
//                             {...field}
//                             disablePortal
//                             id="productCategoryId"
//                             defaultValue={
//                               productCategories && productCategories[0]
//                             }
//                             options={productCategories}
//                             getOptionLabel={(option) => option?.categoryName}
//                             // sx={{
//                             //   "& .MuiOutlinedInput-root": {
//                             //     padding: "0px!important",
//                             //   },
//                             // }}
//                             renderInput={(params) => (
//                               <TextField
//                                 {...params}
//                                 size="small"
//                                 error={Boolean(errors.productCategoryId)}
//                                 helperText={
//                                   errors.productCategoryId
//                                     ? errors.productCategoryId.message
//                                     : ""
//                                 }
//                               />
//                             )}
//                             onChange={(e, value) => {
//                               field.onChange(
//                                 value ? value : { productCategoryId: 0 }
//                               ); // Update the form value
//                             }}
//                             // getOptionSelected={(option, value) => option.value === value.value}
//                           />
//                         )}
//                       />
//                       {/* <TextField
//                         sx={{
//                           "& .MuiInputLabel-root": {
//                             color: "grey !important",
//                           },
//                         }}
//                         label="Select Please"
//                         size="small"
//                         select
//                         id="productCategoryId"
//                         name="productCategoryId"
//                         fullWidth
//                         variant="outlined"
//                         defaultValue=""
//                         {...register("productCategoryId", {
//                           required: {
//                             value: true,
//                             message:
//                               LanguageReducer?.languageType
//                                 ?.FIELD_REQUIRED_TEXT,
//                           },
//                         })}
//                         error={
//                           getValues("productCategoryId") === ""
//                             ? Boolean(errors.productCategoryId)
//                             : false
//                         }
//                         helperText={
//                           getValues("productCategoryId") === ""
//                             ? errors.productCategoryId?.message
//                             : ""
//                         }
//                       >
//                         <MenuItem value="" disabled>
//                           Select Please
//                         </MenuItem>
//                         {productCategories.map((productCategory) => {
//                           return (
//                             <MenuItem
//                               key={productCategory.productCategoryId}
//                               value={productCategory.productCategoryId}
//                             >
//                               {productCategory.categoryName}
//                             </MenuItem>
//                           );
//                         })}
//                       </TextField> */}
//                     </Grid>
//                     <Grid item xs={1}>
//                       <Button
//                         onClick={handleOpen}
//                         sx={{
//                           ...styleSheet.addStoreButton,
//                           padding: "0px",
//                           height: "40px !important",
//                           minWidth: "40px !important",
//                         }}
//                         variant="contained"
//                       >
//                         +
//                       </Button>
//                     </Grid>
//                   </Grid>
//                 </Grid>
//                 <Grid item md={6} xs={12}>
//                   <InputLabel required sx={styleSheet.inputLabelAddProduct}>
//                     {LanguageReducer?.languageType?.ENTER_WEIGHT_TEXT}
//                   </InputLabel>
//                   <TextField
//                     placeholder="Weight"
//                     onFocus={handleFocus}
//                     type="number"
//                     size="small"
//                     id="weight"
//                     name="weight"
//                     inputProps={{
//                       step: "any",
//                     }}
//                     fullWidth
//                     variant="outlined"
//                     {...register("weight", {
//                       required: {
//                         value: true,
//                         message:
//                           LanguageReducer?.languageType?.FIELD_REQUIRED_TEXT,
//                       },
//                       // pattern: {
//                       //   value: /^[0-9]\d*$/,
//                       //   message:
//                       //     LanguageReducer?.languageType
//                       //       ?.WEIGHT_MUST_BE_GREATER_THAN_ZERO_TOAST,
//                       // },
//                     })}
//                     error={Boolean(errors.weight)} // set error prop
//                     helperText={errors.weight?.message}
//                   ></TextField>
//                 </Grid>
//               </Grid>
//               <Grid container spacing={2}>
//                 <Grid item md={6} xs={12}>
//                   <InputLabel required sx={styleSheet.inputLabelAddProduct}>
//                     {LanguageReducer?.languageType?.ENTER_SALE_PRICE_TEXT}
//                   </InputLabel>
//                   <TextField
//                     placeholder="Price"
//                     type="number"
//                     onFocus={handleFocus}
//                     size="small"
//                     id="price"
//                     inputProps={{
//                       step: "any",
//                     }}
//                     name="price"
//                     fullWidth
//                     variant="outlined"
//                     {...register("price", {
//                       required: {
//                         value: true,
//                         message:
//                           LanguageReducer?.languageType?.FIELD_REQUIRED_TEXT,
//                       },
//                       pattern: {
//                         value: /^[1-9]\d*$/,
//                         message:
//                           LanguageReducer?.languageType
//                             ?.PRICE_MUST_BE_GREATER_THAN_ZERO_TOAST,
//                       },
//                     })}
//                     error={Boolean(errors.price)} // set error prop
//                     helperText={errors.price?.message}
//                   ></TextField>
//                 </Grid>
//                 <Grid item md={6} xs={12}>
//                   <InputLabel required sx={styleSheet.inputLabelAddProduct}>
//                     {LanguageReducer?.languageType?.ENTER_PURCHASE_PRICE_TEXT}
//                   </InputLabel>
//                   <TextField
//                     placeholder="Purchase Price"
//                     type="number"
//                     size="small"
//                     onFocus={handleFocus}
//                     id="purchasePrice"
//                     name="purchasePrice"
//                     inputProps={{
//                       step: "any",
//                     }}
//                     fullWidth
//                     variant="outlined"
//                     {...register("purchasePrice", {
//                       required: {
//                         value: true,
//                         message:
//                           LanguageReducer?.languageType?.FIELD_REQUIRED_TEXT,
//                       },
//                       pattern: {
//                         value: /^[1-9]\d*$/,
//                         message:
//                           LanguageReducer?.languageType
//                             ?.PURCHASE_PRICE_MUST_BE_GREATER_THAN_ZERO_TOAST,
//                       },
//                     })}
//                     error={Boolean(errors.purchasePrice)} // set error prop
//                     helperText={errors.purchasePrice?.message}
//                   ></TextField>
//                   {isLowerPrice && (
//                     <FormLabel sx={{ fontSize: "10px" }}>
//                       *Your Purchase price is greater than sale price
//                     </FormLabel>
//                   )}
//                 </Grid>
//               </Grid>
//             </Grid>
//           </Grid>
//           <br />
//           <br />
//           <br />
//           <br />
//           <Grid container spacing={8}>
//             <Grid item md={6} xs={12}>
//               <Typography sx={styleSheet.productsHeading} variant="h5">
//                 {LanguageReducer?.languageType?.INVENTORY_TEXT}
//               </Typography>
//               <Grid item XS={12}>
//                 <FormGroup>
//                   <FormControlLabel
//                     onChange={(e) => {
//                       setTrackInventoryCheckbox(!trackInventoryCheckbox);
//                     }}
//                     value={trackInventoryCheckbox}
//                     control={
//                       <Checkbox
//                         sx={{
//                           color: "var(--primary-color)",
//                           "&.Mui-checked": {
//                             color: "var(--primary-color)",
//                           },
//                         }}
//                         checked={trackInventoryCheckbox}
//                       />
//                     }
//                     label={LanguageReducer?.languageType?.TRACK_INVENTORY_TEXT}
//                   />
//                 </FormGroup>
//               </Grid>
//               <Grid item xs={12}>
//                 <Box
//                   alignContent={"center"}
//                   display={"flex"}
//                   justifyContent={"space-between"}
//                 >
//                   <InputLabel required sx={styleSheet.inputLabelAddProduct}>
//                     {LanguageReducer?.languageType?.ENTER_SKU_TEXT}
//                   </InputLabel>
//                   <FormGroup sx={{ marginTop: "15px" }}>
//                     <FormControlLabel
//                       onChange={(e) => {
//                         handleAutoGenerate(e);
//                       }}
//                       value={autoGenerateSku}
//                       control={
//                         <Checkbox
//                           sx={{
//                             color: "var(--primary-color)",
//                             "&.Mui-checked": {
//                               color: "var(--primary-color)",
//                             },
//                           }}
//                           checked={autoGenerateSku}
//                         />
//                       }
//                       label={"Auto Generate Sku"}
//                     />
//                   </FormGroup>
//                 </Box>
//                 <TextField
//                   placeholder="SKU"
//                   size="small"
//                   onFocus={handleFocus}
//                   id="SKU"
//                   name="SKU"
//                   fullWidth
//                   variant="outlined"
//                   {...register("SKU", {
//                     required: {
//                       value: true,
//                       message:
//                         LanguageReducer?.languageType?.FIELD_REQUIRED_TEXT,
//                     },
//                     pattern: {
//                       value: /^(?!\s*$).+/,
//                       message:
//                         LanguageReducer?.languageType
//                           ?.INPUT_SHOULD_NOT_BE_ONLY_SPACES,
//                     },
//                   })}
//                   error={Boolean(errors.SKU)} // set error prop
//                   helperText={errors.SKU?.message}
//                 ></TextField>
//               </Grid>
//               <br />
//               {!optionsCheckbox ? (
//                 trackInventoryCheckbox ? (
//                   <Grid item xs={12}>
//                     <TableContainer component={Paper}>
//                       <Table fullWidth aria-label="customized table">
//                         <TableBody>
//                           {productStations.map((row, i) => (
//                             <StyledTableRow key={row.productStationId}>
//                               <StyledTableCell
//                                 align="center"
//                                 component="th"
//                                 scope="row"
//                               >
//                                 {row.sname}
//                               </StyledTableCell>
//                               <StyledTableCell align="right">
//                                 <Box display={"flex"} gap={1}>
//                                   <TextField
//                                     onChange={(e) => {
//                                       let newArr = [...stationValues];
//                                       newArr[i] = {
//                                         productStationId: row.productStationId,
//                                         quantityAvailable: e.target.value,
//                                         lowQuantityLimit: newArr[i]
//                                           ?.lowQuantityLimit
//                                           ? newArr[i].lowQuantityLimit
//                                           : 0,
//                                       };
//                                       setStationValues(newArr);
//                                     }}
//                                     defaulValue="0"
//                                     min={0}
//                                     type="number"
//                                     size="small"
//                                     onFocus={handleFocus}
//                                     fullWidth
//                                     variant="outlined"
//                                     label="Quantity"
//                                   ></TextField>
//                                   <TextField
//                                     onChange={(e) => {
//                                       let newArr = [...stationValues];
//                                       newArr[i] = {
//                                         productStationId: row.productStationId,
//                                         lowQuantityLimit: e.target.value,
//                                         quantityAvailable: newArr[i]
//                                           ?.quantityAvailable
//                                           ? newArr[i].quantityAvailable
//                                           : 0,
//                                       };
//                                       setStationValues(newArr);
//                                     }}
//                                     defaulValue="0"
//                                     min={0}
//                                     type="number"
//                                     size="small"
//                                     onFocus={handleFocus}
//                                     fullWidth
//                                     variant="outlined"
//                                     label="Low Quantity Amount"
//                                   ></TextField>
//                                 </Box>
//                               </StyledTableCell>
//                             </StyledTableRow>
//                           ))}
//                         </TableBody>
//                       </Table>
//                     </TableContainer>
//                   </Grid>
//                 ) : null
//               ) : null}
//               <FormGroup>
//                 <FormControlLabel
//                   onChange={(e) => {
//                     setOptionsCheckbox(!optionsCheckbox);
//                     setCombinations([]);
//                     setTempCombinations([]);
//                   }}
//                   value={optionsCheckbox}
//                   control={
//                     <Checkbox
//                       sx={{
//                         color: "var(--primary-color)",
//                         "&.Mui-checked": {
//                           color: "var(--primary-color)",
//                         },
//                       }}
//                     />
//                   }
//                   label={
//                     LanguageReducer?.languageType?.THIS_PRODUCT_HAS_OPTIONS_TEXT
//                   }
//                 />
//               </FormGroup>
//               {optionsCheckbox ? (
//                 <>
//                   {inputFields.map((data, index) => {
//                     return (
//                       <Fragment key={index}>
//                         <Stack direction="row">
//                           <InputLabel sx={styleSheet.inputLabelAddProduct}>
//                             {LanguageReducer?.languageType?.OPTION_NAME_TEXT}
//                           </InputLabel>
//                           {inputFields.length !== 0 ? (
//                             <>
//                               <IconButton
//                                 sx={{ marginLeft: "auto", color: "red" }}
//                                 aria-label="delete"
//                                 onClick={() => removeInputFields(index)}
//                               >
//                                 <DeleteIcon />
//                               </IconButton>{" "}
//                             </>
//                           ) : (
//                             ""
//                           )}
//                         </Stack>

//                         <TextField
//                           onChange={(evnt) => handleChange(index, evnt)}
//                           defaultValue=""
//                           select
//                           size="small"
//                           // onFocus={handleFocus}
//                           fullWidth
//                           variant="outlined"
//                         >
//                           <MenuItem value="" disabled></MenuItem>
//                           {allProductOptions?.map((allProductOption) => {
//                             let disabled = false;

//                             if (inputFields.length > 0) {
//                               if (
//                                 inputFields.find(
//                                   (x) =>
//                                     x.selectedOption == allProductOption?.id
//                                 )
//                               ) {
//                                 disabled = true;
//                               }
//                             }
//                             return (
//                               <MenuItem
//                                 key={allProductOption.id}
//                                 value={allProductOption.id}
//                                 disabled={disabled}
//                               >
//                                 {allProductOption.text}
//                               </MenuItem>
//                             );
//                           })}
//                         </TextField>
//                         <InputLabel sx={styleSheet.inputLabelAddProduct}>
//                           {"Option Value"}
//                         </InputLabel>

//                         <Autocomplete
//                           multiple
//                           id="tags-filled"
//                           variant="outlined"
//                           size="small"
//                           onFocus={handleFocus}
//                           onKeyDown={(e) => handleKeyDown(e, index)} // Added keydown event handler
//                           onChange={(e, value) => {
//                             const list = [...inputFields];
//                             list[index].options = value;
//                             setInputFields(list);
//                             setSelected([]);
//                           }}
//                           options={[]}
//                           freeSolo
//                           renderTags={(value, getTagProps) => {
//                             return inputFields[index].options.map(
//                               (option, index) => (
//                                 <Chip
//                                   key={index}
//                                   variant="outlined"
//                                   size="small"
//                                   label={option}
//                                   {...getTagProps({ index })}
//                                 />
//                               )
//                             );
//                           }}
//                           renderInput={(params) => (
//                             <TextField
//                               {...params}
//                               variant="outlined"
//                               size="small"
//                               placeholder={
//                                 optionValuePlaceHolder
//                                   ? optionValuePlaceHolder[index]
//                                   : "Select option"
//                               }
//                             />
//                           )}
//                         />
//                       </Fragment>
//                     );
//                   })}
//                   <Button
//                     sx={{ ...styleSheet.addStoreButton, marginTop: "10px" }}
//                     fullWidth
//                     variant="contained"
//                     onClick={addInputField}
//                   >
//                     + {LanguageReducer?.languageType?.ADD_OPTION_TEXT}
//                   </Button>
//                 </>
//               ) : null}
//             </Grid>
//             <Grid item md={6} xs={12}>
//               <Typography sx={styleSheet.productsHeading} variant="h5">
//                 {LanguageReducer?.languageType?.VARIANTS_TEXT}
//               </Typography>
//               <br />
//               <Typography sx={styleSheet.inventoryMethodHeading} variant="h6">
//                 {LanguageReducer?.languageType?.AVAILABLE_INVENTORY_AT_TEXT}
//                 {LanguageReducer?.languageType?.ALL_LOCATION_TEXT}
//               </Typography>
//               <hr />
//               <FormGroup>
//                 <Box sx={{ width: "100%" }}>
//                   <Paper sx={{ width: "100%", mb: 2 }}>
//                     {optionsCheckbox ? (
//                       <EnhancedTableToolbar
//                         numSelected={selected.length}
//                         handleOpenPrices={handleOpenPrices}
//                         handleOpenQuantities={handleOpenQuantities}
//                         handleOpenSKU={handleOpenSKU}
//                         handleCloseQuantities={handleCloseQuantities}
//                         handleCloseSKU={handleCloseSKU}
//                         handleClosePrices={handleClosePrices}
//                       />
//                     ) : null}
//                     <TableContainer>
//                       <Table
//                         sx={{ width: "100%" }}
//                         aria-labelledby="tableTitle"
//                         size={"small"}
//                       >
//                         <TableHead>
//                           <TableRow>
//                             <TableCell padding="checkbox">
//                               <Checkbox
//                                 sx={{
//                                   color: "var(--primary-color)",
//                                   "&.Mui-checked": {
//                                     color: "var(--primary-color)",
//                                   },
//                                 }}
//                                 indeterminate={
//                                   selected.length > 0 &&
//                                   selected.length < combinations.length
//                                 }
//                                 checked={
//                                   combinations.length > 0 &&
//                                   selected.length === combinations.length
//                                 }
//                                 onChange={handleSelectAllClick}
//                                 inputProps={{
//                                   "aria-label": "select all desserts",
//                                 }}
//                               />
//                             </TableCell>
//                             {headCells.map((headCell) => (
//                               <TableCell
//                                 key={headCell.id}
//                                 align={headCell.numeric ? "right" : "left"}
//                                 padding={
//                                   headCell.disablePadding ? "none" : "normal"
//                                 }
//                               >
//                                 <TableSortLabel>
//                                   {headCell.label}
//                                 </TableSortLabel>
//                               </TableCell>
//                             ))}
//                           </TableRow>
//                         </TableHead>
//                         {optionsCheckbox ? (
//                           <TableBody>
//                             {combinations.map((combination, index) => {
//                               const isItemSelected = isSelected(index);
//                               const labelId = `enhanced-table-checkbox-${index}`;
//                               return (
//                                 <TableRow
//                                   hover
//                                   onClick={(event) => handleClick(event, index)}
//                                   role="checkbox"
//                                   aria-checked={isItemSelected}
//                                   tabIndex={-1}
//                                   key={index}
//                                   selected={isItemSelected}
//                                   sx={{ cursor: "pointer" }}
//                                 >
//                                   <TableCell padding="checkbox">
//                                     <Checkbox
//                                       sx={{
//                                         color: "var(--primary-color)",
//                                         "&.Mui-checked": {
//                                           color: "var(--primary-color)",
//                                         },
//                                       }}
//                                       checked={isItemSelected}
//                                       inputProps={{
//                                         "aria-labelledby": labelId,
//                                       }}
//                                     />
//                                   </TableCell>
//                                   <TableCell
//                                     component="th"
//                                     id={labelId}
//                                     scope="row"
//                                     padding="none"
//                                   >
//                                     <CardHeader
//                                       avatar={
//                                         <Avatar
//                                           variant="square"
//                                           src={ImageIcon}
//                                           aria-label="Image"
//                                         />
//                                       }
//                                       title={combination.variants?.map(
//                                         (option, optionIndex) =>
//                                           optionIndex ==
//                                           combination.variants?.length - 1
//                                             ? `${option}`
//                                             : `${option}/`
//                                       )}
//                                       subheader={
//                                         combination.SKU == ""
//                                           ? getValues("SKU") + "-" + index
//                                           : combination.SKU
//                                       }
//                                     />
//                                   </TableCell>
//                                   <TableCell align="left">
//                                     <CardHeader
//                                       avatar={<span></span>}
//                                       title={combination.prices}
//                                       subheader={`${
//                                         combination.quantities
//                                       } Available at ${
//                                         combination.stationIds?.length
//                                           ? combination.stationIds.length
//                                           : 0
//                                       } locations`}
//                                     />
//                                   </TableCell>
//                                 </TableRow>
//                               );
//                             })}
//                           </TableBody>
//                         ) : null}
//                       </Table>
//                     </TableContainer>
//                   </Paper>
//                 </Box>
//               </FormGroup>
//               <div
//                 style={{
//                   paddingTop: "20px",
//                   textAlign: "Right",
//                   alignItems: "Right",
//                 }}
//               >
//                 {isLoading ? (
//                   <Button
//                     fullWidth
//                     variant="contained"
//                     sx={styleSheet.addStoreButton}
//                     type="submit"
//                   >
//                     <CircularProgress sx={{ color: "white" }} />
//                   </Button>
//                 ) : (
//                   <Button
//                     fullWidth
//                     variant="contained"
//                     sx={styleSheet.addStoreButton}
//                     type="submit"
//                   >
//                     {LanguageReducer?.languageType?.CREATE_PRODUCT_TEXT}
//                   </Button>
//                 )}
//               </div>
//             </Grid>
//             <Grid style={{ paddingTop: "0px" }} item md={6} xs={12}></Grid>
//           </Grid>
//         </form>
//       </div>
//       <br />
//       <br />
//       <br />
//       <br />
//       <Dialog
//         open={open}
//         TransitionComponent={Transition}
//         keepMounted
//         onClose={handleClose}
//         maxWidth="md"
//         sx={styleSheet.modelMainClassWithImage}
//         aria-describedby="alert-dialog-slide-description"
//       >
//         <DialogContent sx={{ ...styleSheet.modelContentArea, width: "600px" }}>
//           <DialogContentText id="alert-dialog-slide-description">
//             <Box sx={styleSheet.editProductsHeadingAndUpload}>
//               <Typography sx={styleSheet.editProductsHeading} variant="h4">
//                 {LanguageReducer?.languageType?.ADD_CATEGORY_TEXT}
//               </Typography>
//             </Box>
//             <Grid container spacing={2} sx={{ mt: "5px" }}>
//               <Grid item sm={12} sx={{ mt: "10px" }}>
//                 <Divider />
//               </Grid>
//               <Grid item sm={12}>
//                 <InputLabel sx={styleSheet.inputLabelAddProduct}>
//                   {LanguageReducer?.languageType?.CATEGORY_NAME_TEXT}
//                 </InputLabel>
//                 <TextField
//                   placeholder="Category Name"
//                   value={categoryName}
//                   onChange={(e) => {
//                     setCategoryName(e.target.value);
//                   }}
//                   fullWidth
//                   variant="outlined"
//                   onFocus={handleFocus}
//                   size="small"
//                 />
//               </Grid>
//             </Grid>
//           </DialogContentText>
//         </DialogContent>
//         <DialogActions>
//           <Button
//             fullWidth
//             variant="contained"
//             sx={styleSheet.modalDismissButton}
//             onClick={handleClose}
//           >
//             {LanguageReducer?.languageType?.DISMISS_TEXT}
//           </Button>
//           <Button
//             fullWidth
//             variant="contained"
//             sx={styleSheet.modalCarrierSubmitButton}
//             onClick={createCategory}
//           >
//             {LanguageReducer?.languageType?.ADD_CATEGORY_TEXT}
//           </Button>
//         </DialogActions>
//       </Dialog>
//       <Dialog
//         fullWidth
//         open={openSKU}
//         TransitionComponent={Transition}
//         keepMounted
//         onClose={handleCloseSKU}
//         maxWidth="sm"
//         sx={styleSheet.modelMainClassWithImage}
//         aria-describedby="alert-dialog-slide-description"
//       >
//         <DialogContent sx={{ ...styleSheet.modelContentArea }}>
//           <DialogContentText id="alert-dialog-slide-description">
//             <Box sx={styleSheet.editProductsHeadingAndUpload}>
//               <Typography sx={styleSheet.editProductsHeading} variant="h4">
//                 {LanguageReducer?.languageType?.EDIT_SKU_TEXT}
//               </Typography>
//             </Box>
//             <Grid container spacing={2} sx={{ mt: "5px" }}>
//               <Grid item sm={12} sx={{ mt: "10px" }}>
//                 <Divider />
//               </Grid>
//               <Grid item xs={12}>
//                 <TableContainer component={Paper}>
//                   <Table fullWidth aria-label="customized table">
//                     <TableBody>
//                       {selected.map((items, index) => {
//                         return (
//                           <StyledTableRow key={index}>
//                             <StyledTableCell
//                               align="center"
//                               component="th"
//                               scope="row"
//                             >
//                               {combinations[items]?.variants?.map(
//                                 (option, optionIndex) =>
//                                   optionIndex ==
//                                   combinations[items]?.variants?.length - 1
//                                     ? `${option}`
//                                     : `${option}/`
//                               )}
//                             </StyledTableCell>
//                             <StyledTableCell align="right">
//                               <TextField
//                                 placeholder="SKU"
//                                 onChange={(e) => {
//                                   let SKUArr = [...tempCombinations];
//                                   SKUArr[items] = {
//                                     ...SKUArr[items],
//                                     SKU: e.target.value,
//                                   };
//                                   setTempCombinations(SKUArr);
//                                 }}
//                                 value={tempCombinations[items]?.SKU}
//                                 onFocus={handleFocus}
//                                 fullWidth
//                                 variant="outlined"
//                                 size="small"
//                               ></TextField>
//                             </StyledTableCell>
//                           </StyledTableRow>
//                         );
//                       })}
//                     </TableBody>
//                   </Table>
//                 </TableContainer>
//               </Grid>
//             </Grid>
//           </DialogContentText>
//         </DialogContent>

//         <DialogActions>
//           <Button
//             fullWidth
//             variant="contained"
//             sx={styleSheet.modalDismissButton}
//             onClick={handleCloseSKU}
//           >
//             {LanguageReducer?.languageType?.DISMISS_TEXT}
//           </Button>
//           <Button
//             fullWidth
//             variant="contained"
//             sx={styleSheet.modalCarrierSubmitButton}
//             onClick={() => {
//               setCombinations(tempCombinations);
//               handleCloseSKU();
//             }}
//           >
//             {LanguageReducer?.languageType?.SUBMIT_TEXT}
//           </Button>
//         </DialogActions>
//       </Dialog>
//       <Dialog
//         fullWidth
//         open={openPrices}
//         TransitionComponent={Transition}
//         keepMounted
//         onClose={handleClosePrices}
//         maxWidth="sm"
//         sx={styleSheet.modelMainClassWithImage}
//         aria-describedby="alert-dialog-slide-description"
//       >
//         <DialogContent sx={{ ...styleSheet.modelContentArea }}>
//           <DialogContentText id="alert-dialog-slide-description">
//             <Box sx={styleSheet.editProductsHeadingAndUpload}>
//               <Typography sx={styleSheet.editProductsHeading} variant="h4">
//                 {LanguageReducer?.languageType?.EDIT_PRICES_TEXT}
//               </Typography>
//             </Box>
//             <Grid container spacing={2} sx={{ mt: "5px" }}>
//               <Grid item sm={12} sx={{ mt: "10px" }}>
//                 <Divider />
//               </Grid>
//               <Grid item xs={12}>
//                 <TableContainer component={Paper}>
//                   <Table fullWidth aria-label="customized table">
//                     <TableBody>
//                       {selected.map((items, index) => {
//                         return (
//                           <StyledTableRow key={index}>
//                             <StyledTableCell
//                               align="center"
//                               component="th"
//                               scope="row"
//                             >
//                               {combinations[items]?.variants?.map(
//                                 (option, optionIndex) =>
//                                   optionIndex ==
//                                   combinations[items]?.variants?.length - 1
//                                     ? `${option}`
//                                     : `${option}/`
//                               )}
//                             </StyledTableCell>
//                             <StyledTableCell align="right">
//                               <TextField
//                                 placeholder="Prices"
//                                 onChange={(e) => {
//                                   let priceArr = [...tempCombinations];
//                                   priceArr[items] = {
//                                     ...priceArr[items],
//                                     prices: e.target.value,
//                                   };
//                                   setTempCombinations(priceArr);
//                                 }}
//                                 value={tempCombinations[items]?.prices}
//                                 fullWidth
//                                 variant="outlined"
//                                 size="small"
//                                 onFocus={handleFocus}
//                               ></TextField>
//                             </StyledTableCell>
//                           </StyledTableRow>
//                         );
//                       })}
//                     </TableBody>
//                   </Table>
//                 </TableContainer>
//               </Grid>
//             </Grid>
//           </DialogContentText>
//         </DialogContent>
//         <DialogActions>
//           <Button
//             fullWidth
//             variant="contained"
//             sx={styleSheet.modalDismissButton}
//             onClick={handleClosePrices}
//           >
//             {LanguageReducer?.languageType?.DISMISS_TEXT}
//           </Button>
//           <Button
//             fullWidth
//             variant="contained"
//             sx={styleSheet.modalCarrierSubmitButton}
//             onClick={() => {
//               setCombinations(tempCombinations);
//               handleClosePrices();
//             }}
//           >
//             {LanguageReducer?.languageType?.SUBMIT_TEXT}
//           </Button>
//         </DialogActions>
//       </Dialog>

//       <Dialog
//         fullWidth
//         open={openQuantities}
//         TransitionComponent={Transition}
//         keepMounted
//         onClose={handleCloseQuantities}
//         maxWidth="md"
//         sx={styleSheet.modelMainClassWithImage}
//         aria-describedby="alert-dialog-slide-description"
//       >
//         <DialogContent sx={{ ...styleSheet.modelContentArea }}>
//           <DialogContentText id="alert-dialog-slide-description">
//             <Box sx={styleSheet.editProductsHeadingAndUpload}>
//               <Typography sx={styleSheet.editProductsHeading} variant="h4">
//                 {LanguageReducer?.languageType?.EDIT_QUNATITIES_TEXT}
//               </Typography>
//             </Box>
//             <Grid container spacing={2} sx={{ mt: "5px" }}>
//               <Grid item sm={12} sx={{ mt: "10px" }}>
//                 <Divider />
//               </Grid>
//               <Grid item xs={12}>
//                 <Table fullWidth aria-label="customized table">
//                   <TableBody>
//                     {selected.map((items, index) => {
//                       return <>{getValueFromRow(items, index)}</>;
//                     })}
//                   </TableBody>
//                 </Table>
//               </Grid>
//             </Grid>
//           </DialogContentText>
//         </DialogContent>
//         <DialogActions>
//           <Button
//             fullWidth
//             variant="contained"
//             sx={styleSheet.modalDismissButton}
//             onClick={handleCloseQuantities}
//           >
//             {LanguageReducer?.languageType?.DISMISS_TEXT}
//           </Button>
//           <Button
//             fullWidth
//             variant="contained"
//             sx={styleSheet.modalCarrierSubmitButton}
//             onClick={() => {
//               setCombinations(tempCombinations);
//               handleCloseQuantities();
//             }}
//           >
//             {"Add Quantity"}
//           </Button>
//         </DialogActions>
//       </Dialog>
//     </Box>
//   );
// }
// export default Products;
