using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Shipra.Backend.API.Application.Common.Helpers;
using Shipra.Backend.API.Application.Common.Security;
using Shipra.Backend.API.Application.Features.CommonFeatures.Query.GetAllLookupAdjustReasonQuery;
using Shipra.Backend.API.Application.Features.InventorySalesFeatures.Query.ExcelExportInventorySalesSummary;
using Shipra.Backend.API.Application.Features.InventorySalesFeatures.Query.ExcelExportSalesInventory;
using Shipra.Backend.API.Application.Features.InventorySalesFeatures.Query.GetAllInventorySales;
using Shipra.Backend.API.Application.Features.InventorySalesFeatures.Query.GetInventorySalesSummary;
using Shipra.Backend.API.Application.Features.InventorySalesFeatures.Query.GetPDFInventorySales;
using Shipra.Backend.API.Application.Features.InventorySalesFeatures.Query.GetPDFInventorySalesSummary;
using Shipra.Backend.API.Application.Features.OrderFeatures.Commands.UploadFileRegular;
using Shipra.Backend.API.Application.Features.ProductFeatures.Commands.CreateImageGallery;
using Shipra.Backend.API.Application.Features.ProductFeatures.Commands.CreateProduct;
using Shipra.Backend.API.Application.Features.ProductFeatures.Commands.CreateProductFromShipraToShopify;
using Shipra.Backend.API.Application.Features.ProductFeatures.Commands.CreateSellerProduct;
using Shipra.Backend.API.Application.Features.ProductFeatures.Commands.DeleteProductMedia;
using Shipra.Backend.API.Application.Features.ProductFeatures.Commands.DisableProduct;
using Shipra.Backend.API.Application.Features.ProductFeatures.Commands.DisableProductStock;
using Shipra.Backend.API.Application.Features.ProductFeatures.Commands.EnableProduct;
using Shipra.Backend.API.Application.Features.ProductFeatures.Commands.EnableProductStock;
using Shipra.Backend.API.Application.Features.ProductFeatures.Commands.GenerateProductLinkToken;
using Shipra.Backend.API.Application.Features.ProductFeatures.Commands.QuickAddProductOption;
using Shipra.Backend.API.Application.Features.ProductFeatures.Commands.UpdateProduct;
using Shipra.Backend.API.Application.Features.ProductFeatures.Commands.UpdateProductStockQuantityByReason;
using Shipra.Backend.API.Application.Features.ProductFeatures.Commands.UploadProductFile;
using Shipra.Backend.API.Application.Features.ProductFeatures.Commands.UploadProductFiles;
using Shipra.Backend.API.Application.Features.ProductFeatures.Commands.UploadProductRegular;
using Shipra.Backend.API.Application.Features.ProductFeatures.Query.CheckUniqueProductStockSku;
using Shipra.Backend.API.Application.Features.ProductFeatures.Query.CheckUniqueProductStockSkus;
using Shipra.Backend.API.Application.Features.ProductFeatures.Query.DownloadInventoryHistorySummaryExcel;
using Shipra.Backend.API.Application.Features.ProductFeatures.Query.ExcekExportLowQuantityProductStock;
using Shipra.Backend.API.Application.Features.ProductFeatures.Query.ExcelExportDriverExpense;
using Shipra.Backend.API.Application.Features.ProductFeatures.Query.ExcelExportProductInventory;
using Shipra.Backend.API.Application.Features.ProductFeatures.Query.ExcelExportProductInventorySummary;
using Shipra.Backend.API.Application.Features.ProductFeatures.Query.ExcelReportProductCountAvailability;
using Shipra.Backend.API.Application.Features.ProductFeatures.Query.GetAllImageGalleries;
using Shipra.Backend.API.Application.Features.ProductFeatures.Query.GetAllLowQuantityProductStock;
using Shipra.Backend.API.Application.Features.ProductFeatures.Query.GetAllProductInventorySummary;
using Shipra.Backend.API.Application.Features.ProductFeatures.Query.GetAllProducts;
using Shipra.Backend.API.Application.Features.ProductFeatures.Query.GetAllStoreWithTokenByProductId;
using Shipra.Backend.API.Application.Features.ProductFeatures.Query.GetMarketPlaceProducts;
using Shipra.Backend.API.Application.Features.ProductFeatures.Query.GetProductById;
using Shipra.Backend.API.Application.Features.ProductFeatures.Query.GetProductInventory;
using Shipra.Backend.API.Application.Features.ProductFeatures.Query.GetProductSampleFile;
using Shipra.Backend.API.Application.Features.ProductFeatures.Query.GetProductStockByProductStockId;
using Shipra.Backend.API.Application.Features.ProductFeatures.Query.GetProductStockHistoryByStockId;
using Shipra.Backend.API.Application.Features.ProductFeatures.Query.GetProductStockPriceByProductStockID;
using Shipra.Backend.API.Application.Features.ProductFeatures.Query.GetProductStoresForSelection;
using Shipra.Backend.API.Application.Features.ProductFeatures.Query.GetUniqueAutoGeneratedSku;
using Shipra.Backend.API.Application.Features.ProductFeatures.Query.LookupProductStockStatusForSelection;
using Shipra.Backend.API.Application.Features.SaleChannelProcessFeature.Command.SyncSaleChannelInventory;
using Shipra.Backend.API.Application.Features.StoreFeatures.Command.AssignStoreProduct;
using Shipra.Backend.API.Application.Features.StoreFeatures.Command.DeleteStoreProduct;
using Shipra.Backend.API.Application.Features.ProductFeatures.Query.GetVariantsWithoutStation;
using Shipra.Backend.API.Application.Features.ProductFeatures.Commands.AssignStationToVariants;
using Shipra.Backend.API.Application.Helpers;
using Shipra.Backend.API.Application.Helpers.Reporting;

namespace Shipra.Backend.API.Web.Api;
[Authorize]
public class ProductController : BaseApiController
{
  public ProductController(IServiceProvider serviceProvider) : base(serviceProvider)
  {
  }

  #region Commmand

  [HttpPost("CreateProduct")]
  public async Task<ActionResult> CreateProduct([FromBody] CreateProductCommand request, CancellationToken cancellationToken = default)
  {
    var response = await Mediator.Send(request, cancellationToken);
    return Ok(response);
  }

  [HttpPost("CreateProductFromShipraToShopify")]
  public async Task<ActionResult> CreateProduct([FromBody] CreateProductFromShipraToShopifyCommand request, CancellationToken cancellationToken = default)
  {
    var response = await Mediator.Send(request, cancellationToken);
    return Ok(response);
  }

  [HttpPost("DisableProductById")]
  public async Task<ActionResult> DisableProductById([FromBody] DisableProductCommand request, CancellationToken cancellationToken = default)
  {
    var response = await Mediator.Send(request, cancellationToken);
    return Ok(response);
  }
  [HttpPost("EnableProductById")]
  public async Task<ActionResult> EnableProductById([FromBody] EnableProductCommand request, CancellationToken cancellationToken = default)
  {
    var response = await Mediator.Send(request, cancellationToken);
    return Ok(response);
  }
  [HttpPost("QuickAddProductOption")]
  public async Task<ActionResult> CreateQuickAddProductOption([FromBody] QuickAddProductOptionCommand request, CancellationToken cancellationToken = default)
  {
    var response = await Mediator.Send(request, cancellationToken);
    return Ok(response);
  }

  [HttpGet("GetVariantsWithoutStation")]
  public async Task<ActionResult> GetVariantsWithoutStation(CancellationToken cancellationToken = default)
  {
      var response = await Mediator.Send(new GetVariantsWithoutStationQuery(), cancellationToken);
      return Ok(response);
  }

  [HttpPost("AssignStationToVariants")]
  public async Task<ActionResult> AssignStationToVariants([FromBody] AssignStationToVariantsCommand request, CancellationToken cancellationToken = default)
  {
      var response = await Mediator.Send(request, cancellationToken);
      return Ok(response);
  }

  [HttpPost("UpdateProduct")]
  public async Task<ActionResult> UpdateProduct([FromBody] UpdateProductCommand request, CancellationToken cancellationToken = default)
  {
    var response = await Mediator.Send(request, cancellationToken);
    return Ok(response);
  }
  [HttpPost("DeleteProductMediaById")]
  public async Task<ActionResult> DeleteProductMediaById([FromBody] DeleteProductMediaCommand request, CancellationToken cancellationToken = default)
  {
    var response = await Mediator.Send(request, cancellationToken);
    return Ok(response);
  }

  [HttpPost("UploadProductFile")]
  public async Task<ActionResult> UploadProductFile([FromForm] UploadProductFileCommand request, CancellationToken cancellationToken = default)
  {
    var response = await Mediator.Send(request, cancellationToken);
    return Ok(response);
  }

  [HttpPost("UploadProductFiles")]
  public async Task<ActionResult> UploadProductFiles([FromForm] UploadProductFilesCommand request, CancellationToken cancellationToken = default)
  {
    var response = await Mediator.Send(request, cancellationToken);
    return Ok(response);
  }

  [HttpPost("UpdateProductStockQuantityByReason")]
  public async Task<ActionResult> UpdateProductStockQuantityByReason([FromBody] UpdateProductStockQuantityByReasonCommand request, CancellationToken cancellationToken = default)
  {
    var response = await Mediator.Send(request, cancellationToken);
    return Ok(response);
  }

  [HttpPost("EnableProductStock")]
  public async Task<ActionResult> EnableProductStock([FromBody] EnableProductStockCommand request, CancellationToken cancellationToken = default)
  {
    var response = await Mediator.Send(request, cancellationToken);
    return Ok(response);
  }

  [HttpPost("DisableProductStock")]
  public async Task<ActionResult> DisableProductStock([FromBody] DisableProductStockCommand request, CancellationToken cancellationToken = default)
  {
    var response = await Mediator.Send(request, cancellationToken);
    return Ok(response);
  }
  //upload UploadProductFile...
  [HttpPost("UploadProducts")]
  public async Task<ActionResult> UploadProducts([FromForm] UploadProductCommand request, CancellationToken cancellationToken = default)
  {
    var response = await Mediator.Send(request, cancellationToken);
    return Ok(response);
  }
  [HttpPost("AssignStoreProduct")]
  public async Task<ActionResult> AssignStoreProduct([FromBody] AssignStoreProductCommand request, CancellationToken cancellationToken = default)
  {
    var response = await Mediator.Send(request, cancellationToken);
    return Ok(response);
  }
  [HttpPost("UnAssignStoreProduct")]
  public async Task<ActionResult> UnAssignStoreProduct([FromBody] UnAssignStoreProductCommand request, CancellationToken cancellationToken = default)
  {
    var response = await Mediator.Send(request, cancellationToken);
    return Ok(response);
  }
  #endregion

  #region query
  [HttpGet("GetProductById")]
  public async Task<ActionResult> GetProductById([FromQuery] GetProductByIdQuery request, CancellationToken cancellationToken = default)
  {
    var response = await Mediator.Send(request, cancellationToken);
    return Ok(response);
  }
  [HttpGet("GetAllStoreWithTokenByProductId")]
  public async Task<ActionResult> GetAllStoreWithTokenByProductId([FromQuery] GetAllStoreWithTokenByProductIdQuery request, CancellationToken cancellationToken = default)
  {
    var response = await Mediator.Send(request, cancellationToken);
    return Ok(response);
  }
  [HttpGet("GetProductStockByProductStockIdForInventory")]
  public async Task<ActionResult> GetProductStockByProductStockIdForInventory([FromQuery] GetProductStockByProductStockIdForInventoryQuery request, CancellationToken cancellationToken = default)
  {
    var response = await Mediator.Send(request, cancellationToken);
    return Ok(response);
  }
  [HttpPost("GetAllProducts")]
  public async Task<ActionResult> GetAllProducts([FromBody] GetAllProductsQuery request, CancellationToken cancellationToken = default)
  {
    var response = await Mediator.Send(request, cancellationToken);
    return Ok(response);
  }

  [HttpGet("GetProductOptionStock")]
  public async Task<ActionResult> GetProductOptionStock([FromQuery] GetProductByIdQuery request, CancellationToken cancellationToken = default)
  {
    var response = await Mediator.Send(request, cancellationToken);
    return Ok(response);
  }
  [HttpGet("CheckUniqueProductStockSku")]
  public async Task<ActionResult> GetProductSku([FromQuery] CheckUniqueProductStockSkuQuery request, CancellationToken cancellationToken = default)
  {
    var response = await Mediator.Send(request, cancellationToken);
    return Ok(response);
  }
  [HttpGet("CheckUniqueProductStockSkus")]
  public async Task<ActionResult> CheckUniqueProductStockSkus([FromQuery] CheckUniqueProductStockSkusCommand request, CancellationToken cancellationToken = default)
  {
    var response = await Mediator.Send(request, cancellationToken);
    return Ok(response);
  }
  [HttpGet("GetUniqueAutogeneratedSku")]
  public async Task<ActionResult> GetUniqueAutogeneratedSku([FromQuery] GetUniqueAutoGeneratedSkuQuery request, CancellationToken cancellationToken = default)
  {
    var response = await Mediator.Send(request, cancellationToken);
    return Ok(response);
  }
  [HttpPost("GetAllLowQuantityProductStock")]
  public async Task<ActionResult> GetAllLowQuantityProductStock([FromBody] GetAllLowQuantityProductStockQuery request, CancellationToken cancellationToken = default)
  {
    var response = await Mediator.Send(request, cancellationToken);
    return Ok(response);
  }
  [HttpPost("ExcekExportLowQuantityProductStock")]
  public async Task<ActionResult> ExcekExportLowQuantityProductStock([FromBody] ExcekExportLowQuantityProductStockQuery request, CancellationToken cancellationToken = default)
  {
    var response = await Mediator.Send(request, cancellationToken);
    return File(response!.Result?.Bytes!, ExcelExportHelper.ExcelContentType, ExcelExportHelper.GetExcelFileName("ProductLowInventory"));
  }
  [HttpPost("GetAllProductInventory")]
  public async Task<ActionResult> GetAllProductInventory([FromBody] GetAllProductInventoryQuery request, CancellationToken cancellationToken = default)
  {
    var response = await Mediator.Send(request, cancellationToken);
    return Ok(response);
  }
  [HttpPost("ExcelExportProductInventory")]
  public async Task<ActionResult> ExcelExportProductInventory([FromBody] ExcelExportProductInventoryQuery request, CancellationToken cancellationToken = default)
  {
    var response = await Mediator.Send(request, cancellationToken);
    return File(response!.Result?.Bytes!, ExcelExportHelper.ExcelContentType, ExcelExportHelper.GetExcelFileName("ProductInventory"));
  }

  [HttpPost("GetAllProductInventorySummary")]
  public async Task<ActionResult> GetAllProductInventorySummary([FromBody] GetAllProductInventorySummaryQuery request, CancellationToken cancellationToken = default)
  {
    var response = await Mediator.Send(request, cancellationToken);
    return Ok(response);
  }

  [HttpPost("ExcelExportProductInventorySummary")]
  public async Task<ActionResult> ExcelExportProductInventorySummary([FromBody] ExcelExportProductInventorySummaryQuery request, CancellationToken cancellationToken = default)
  {
    var response = await Mediator.Send(request, cancellationToken);
    return File(response!.Result?.Bytes!, ExcelExportHelper.ExcelContentType, ExcelExportHelper.GetExcelFileName("ProductInventorySummary"));
  }

  [HttpPost("GetProductStockHistoryByStockId")]
  public async Task<ActionResult> GetProductStockHistoryByStockId([FromBody] GetProductStockHistoryByStockIdQuery request, CancellationToken cancellationToken = default)
  {
    var response = await Mediator.Send(request, cancellationToken);
    return Ok(response);
  }
  [HttpPost("ExcelExportProductStockHistory")]
  public async Task<ActionResult> ExcelExportProductStockHistory([FromBody] ExcelExportProductStockHistoryQuery request, CancellationToken cancellationToken = default)
  {
    var response = await Mediator.Send(request, cancellationToken);
    return File(response!.Result?.Bytes!, ExcelExportHelper.ExcelContentType, ExcelExportHelper.GetExcelFileName("ProductStockHistory"));
  }
  [HttpPost("ExcelExportProductStockCountAvailable")]
  public async Task<ActionResult> ExcelExportProductStockCountAvailable([FromBody] ExcelExportProductStockCountAvailableQuery request, CancellationToken cancellationToken = default)
  {
    var response = await Mediator.Send(request, cancellationToken);
    return File(response!.Result?.Bytes!, ExcelExportHelper.ExcelContentType, ExcelExportHelper.GetExcelFileName("ProductStockCountAvailable"));
  }
  [HttpGet("GetProductStockPriceByProducStockId")]
  public async Task<ActionResult> GetProductStockPriceByProducStockId([FromQuery] GetProductStockPriceByProductStockIdQuery request, CancellationToken cancellationToken = default)
  {
    var response = await Mediator.Send(request, cancellationToken);
    return Ok(response);
  }
  [HttpGet("GetProductStocksForSelection")]
  public async Task<ActionResult> GetProductStocksForSelection([FromQuery] GetProductStocksForSelectionQuery request, CancellationToken cancellationToken = default)
  {
    var response = await Mediator.Send(request, cancellationToken);
    return Ok(response);
  }
  [HttpGet("GetAllAdjustReasonForSelection")]
  public async Task<ActionResult> GetAllAdjustReasonForSelection(CancellationToken cancellationToken = default)
  {
    GetAllLookupAdjustReasonQuery request = new GetAllLookupAdjustReasonQuery();
    var response = await Mediator.Send(request, cancellationToken);
    return Ok(response);
  }
  [HttpGet("GetProductStockStatusForSelectionQuery")]
  public async Task<ActionResult> GetProductStockStatusForSelectionQuery(CancellationToken cancellationToken = default)
  {
    LookupProductStockStatusForSelectionQuery request = new LookupProductStockStatusForSelectionQuery();
    var response = await Mediator.Send(request, cancellationToken);
    return Ok(response);
  }
  [HttpPost("DownloadInventoryHistorySummaryExcel")]
  public async Task<ActionResult> DownloadInventoryHistorySummaryExcel([FromBody] DownloadInventoryHistorySummaryExcelQuery request, CancellationToken cancellationToken = default)
  {
    var response = await Mediator.Send(request, cancellationToken);
    return File(response!.Result?.Bytes!, ExcelExportHelper.ExcelContentType, ExcelExportHelper.GetExcelFileName("ProductInventoryHistory"));
  }
  [HttpGet("GetProductSampleFile")]
  public async Task<ActionResult> GetProductSampleFile(CancellationToken cancellationToken = default)
  {
    GetProductSampleFileQuery request = new();
    var response = await Mediator.Send(request, cancellationToken);
    return Ok(response);
  }
  [HttpPost("SyncSaleChannelInventory")]
  public async Task<ActionResult> SyncSaleChannelInventory([FromBody] SyncSaleChannelInventoryCommand request, CancellationToken cancellationToken = default)
  {
    var response = await Mediator.Send(request, cancellationToken);
    return Ok(response);
  }
  [HttpGet("GenerateProductLinkToken")]
  public async Task<ActionResult> GenerateProductLinkToken([FromQuery] GenerateProductLinkTokenCommand request, CancellationToken cancellationToken = default)
  {
    var response = await Mediator.Send(request, cancellationToken);
    return Ok(response);
  }
  [HttpGet("GetAllImageGalleries")]
  public async Task<ActionResult> GetAllImageGalleries(CancellationToken cancellationToken = default)
  {
    GetAllImageGalleriesQuery request = new();
    var response = await Mediator.Send(request, cancellationToken);
    return Ok(response);
  }
  [HttpPost("CreateImageGallery")]
  public async Task<ActionResult> CreateImageGallery([FromForm] CreateImageGalleryCommand request, CancellationToken cancellationToken = default)
  {
    var response = await Mediator.Send(request, cancellationToken);
    return Ok(response);
  }
  //GetProductStationid
  #endregion

  #region InventorySales
  [HttpPost("GetAllInventorySales")]
  public async Task<ActionResult> GetAllInventorySales([FromBody] GetAllInventorySalesQuery request, CancellationToken cancellationToken = default)
  {
    var response = await Mediator.Send(request, cancellationToken);
    return Ok(response);
  }
  [HttpPost("ExcelExportInventorySales")]
  public async Task<ActionResult> ExcelExportInventorySales([FromBody] ExcelExportInventorySalesQuery request, CancellationToken cancellationToken = default)
  {
    var response = await Mediator.Send(request, cancellationToken);
    return File(response!.Result?.Bytes!, ExcelExportHelper.ExcelContentType, ExcelExportHelper.GetExcelFileName("InventorySales"));
  }
  [HttpPost("GetInventorySalesSummary")]
  public async Task<ActionResult> GetInventorySalesSummary([FromBody] GetInventorySalesSummaryQuery request, CancellationToken cancellationToken = default)
  {
    var response = await Mediator.Send(request, cancellationToken);
    return Ok(response);
  }
  [HttpPost("ExcelExportInventorySalesSummary")]
  public async Task<ActionResult> ExcelExportInventorySalesSummary([FromBody] ExcelExportInventorySalesSummaryQuery request, CancellationToken cancellationToken = default)
  {
    var response = await Mediator.Send(request, cancellationToken);
    return File(response!.Result?.Bytes!, ExcelExportHelper.ExcelContentType, ExcelExportHelper.GetExcelFileName("InventorySalesSummary"));
  }
  [HttpPost("GetPDFInventorySales")]
  public async Task<ActionResult> GetPDFInventorySales([FromBody] GetPDFInventorySalesQuery request, CancellationToken cancellationToken = default)
  {
    var result = await Mediator.Send(request, cancellationToken);

    var file = DirectoryHelper.GetRandomNameForPdf("CRR");
    try
    {
      return File(result.Result!, PDFDocumentGenerator.ContentType, file);
    }
    catch (Exception ex)
    {
      Console.WriteLine($"An error occurred: {ex.Message}");
    }
    return Ok(result);
  }
  [HttpPost("GetPDFInventorySalesSummary")]
  public async Task<ActionResult> GetPDFInventorySalesSummary([FromBody] GetPDFInventorySalesSummaryQuery request, CancellationToken cancellationToken = default)
  {
    var result = await Mediator.Send(request, cancellationToken);

    var file = DirectoryHelper.GetRandomNameForPdf("CRR");
    try
    {
      return File(result.Result!, PDFDocumentGenerator.ContentType, file);
    }
    catch (Exception ex)
    {
      Console.WriteLine($"An error occurred: {ex.Message}");
    }
    return Ok(result);
  }
  //GetAllMarketPlaceProduct//
  [HttpPost("GetAllMarketPlaceProducts")]
  public async Task<ActionResult> GetAllMarketPlaceProducts([FromBody] GetMarketPlaceProductsQuery request, CancellationToken cancellationToken = default)
  {
    var response = await Mediator.Send(request, cancellationToken);
    return Ok(response);
  }
  //CreateMarketPlaceProduct//
  [HttpPost("CreateSellerProduct")]
  public async Task<ActionResult> CreateSellerProduct([FromBody] CreateSellerProductCommand request, CancellationToken cancellationToken = default)
  {
    var response = await Mediator.Send(request, cancellationToken);
    return Ok(response);
  }
  #endregion
}
