using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using DocumentFormat.OpenXml.Bibliography;
using MediatR;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using Shipra.Backend.API.Application.Common;
using Shipra.Backend.API.Application.Common.Constants;
using Shipra.Backend.API.Application.Common.Exceptions;
using Shipra.Backend.API.Application.DTOs;
using Shipra.Backend.API.Application.DTOs.ProductUseCase.Request;
using Shipra.Backend.API.Application.Features.ProductFeatures.Commands.CreateProduct;
using Shipra.Backend.API.Application.Features.ProductFeatures.Query.GetMarketPlaceProducts;
using Shipra.Backend.API.Application.Features.ProductFeatures.Query.GetUniqueAutoGeneratedSku;
using Shipra.Backend.API.Core.Interfaces;
using Shipra.Backend.API.SharedKernel.Interfaces;
using Shipra.Backend.API.SharedKernel.Repository;

namespace Shipra.Backend.API.Application.Features.ProductFeatures.Commands.CreateSellerProduct;
public class CreateSellerProductCommandHandler : RequestHandlerBase<CreateSellerProductCommand, ServiceResultDTO>
{
  private readonly IMediator _mediator;
  
  private readonly IProductRepository _productRepository;

  public CreateSellerProductCommandHandler(IMediator mediator,IStoreRepository storeRepository, IProductRepository productRepository, IServiceProvider serviceProvider, ILogger<CreateSellerProductCommandHandler> logger) : base(serviceProvider, logger)
  {
    _mediator = mediator;
    _productRepository = productRepository;
  }
  protected override async Task<ServiceResultDTO> HandleRequest(CreateSellerProductCommand request, CancellationToken cancellationToken)
  {
    var serviceResultDTO = new ServiceResultDTO();

    try
    {
      var groupedClids = request.Products!.GroupBy(x => x.ClientId);
      foreach (var item in groupedClids)
      {
        var productIds = string.Join(",", item.Select(x => x.ProductId));
        var products = await _productRepository.GetAllProductsByIdsAsync(productIds, item.Key!);
        foreach (var product in products!)
        {
          var skures =  await _mediator.Send(new GetUniqueAutoGeneratedSkuQuery());
          if (skures.IsSuccess)
          {
            dynamic resultObj = skures.Result!;
            var sku = resultObj.sk;
          }
          var productid = product.ProductId!.ToString();
          var (stock, options, media) = await _productRepository.GetAllProductStockAndOptionsByIdAsync(product, item.Key!);
          #region Request 
          var createProductCmd = new CreateProductCommand
          {
            SKU = product.Sku!,
            ProductName = product.ProductName,
            Price = product.Price,
            PurchasePrice = product.PurchasePrice,
            Description = product.Description,
            ProductCategoryId = product.ProductCategoryId,
            FeatureImage = product.FeatureImage,
            Weight = product.Weight,
            HaveOptions = product.HaveOptions.GetValueOrDefault(),
            QuantityAvailable = product.QuantityAvailable,
            StoreId = 0,
            ProductStatusId = product.ProductStatusId,
            TrackInventory = product.TrackInventory,

            ProductMedias = media.Select(m => new ProductMediaRequestModel
            {
              ProductMediaId = m.ProductMediaId,
              ImageGalleryId = m.ImageGalleryId,
              IsFeatured = m.IsFeatured,
            }).ToList(),

            ProductOptions = options.Select(o => new ProductOptionReuqestModel
            {
              ProductOptionsId = o.ProductOptionsId!.ToString(),
              OptionId = o.OptionId.ToString(),
              OptionValue = o.OptionValue,
              DisplayOrder = int.Parse(o.DisplayOrder?.ToString() ?? "0"),
              IsDeleted = o.IsDeleted ?? false

               
            }).ToList(),

            ProductStocks = stock.Select(s => new ProductStockReuqestModel
            {
              ProductStockId = s.ProductStockId,
              ProductId = s.ProductId?.Value.ToString(),   
              Sku = s.Sku,
              Price = s.Price,
              QuantityAvailable = s.QuantityAvailable ?? 0,  
              LowQuantityLimit = int.Parse(s.LowQuantityLimit?.ToString() ?? "0"),
              ProductStationId = s.ProductStationId,
              VarientOption = s.VarientOption,
              ProductStockStatusId = s.ProductStockStatusId,
              ImageGalleryId = s.ImageGalleryId,
              ImageUrl ="",
              Active = s.Active ?? true                      
            }).ToList(),

          };
          #endregion
          var result = await _mediator.Send(createProductCmd);
          serviceResultDTO = new ServiceResultDTO(result);

          return serviceResultDTO;
        }

      }
      return serviceResultDTO;

    }
    catch (Exception ex)
    {

      serviceResultDTO.CreateErrorResponse(ex);
      throw;
    }
  }
}
