import {
  inventoryArabic,
  inventoryChines,
  inventoryEnglish,
  inventoryUrdu,
} from "./inventory/inventory";
import {
  inventorySaleArabic,
  inventorySaleChines,
  inventorySaleEnglish,
  inventorySaleUrdu,
} from "./inventorySale/inventorySale";
import {
  lowInventoryEnglish,
  lowInventoryArabic,
  lowInventoryChines,
  lowInventoryUrdu,
} from "./lowInventory/lowInventory";
import {
  ProductStationArabic,
  ProductStationChines,
  ProductStationEnglish,
  ProductStationUrdu,
} from "./productStation/productStation";
import {
  SaleChannelProductArabic,
  SaleChannelProductChines,
  SaleChannelProductEnglish,
  SaleChannelProductUrdu,
} from "./saleChannelProduct/saleChannelProduct";

export const productsEnglish = {
  ...inventoryEnglish,
  ...lowInventoryEnglish,
  ...inventorySaleEnglish,
  ...SaleChannelProductEnglish,
  ...ProductStationEnglish,
  PRODUCTS_TEXT: "Products",
  PRODUCTS_TEXT_S: "Product(s)",
  PRODUCT_ALL: "All",
  PRODUCT_ACTIVE: "Active",
  PRODUCT_IN_ACTIVE: "In Active",
  PRODUCTS_ADD_PRODUCTS: "Add Products",
  PRODUCTS_SKU: "SKU",
  PRODUCTS_CATEGORY_NAME: "Category Name",
  PRODUCTS_STORE_NAME: "Store Name",
  PRODUCTS_QTY_AVAILABLE: "Qty Available",
  PRODUCTS_WEIGHT: "Weight",
  PRODUCTS_PURCHASE_PRICE: "Purchase Price",
  PRODUCTS_SALE_PRICE: "Sale Price",
  PRODUCTS_STATUS: "Status",
  PRODUCTS_ACTION: "Action",
  PRODUCTS_PRODUCT_DETAIL: "Product Detail",
  PRODUCTS_PRODUCT_DASHBOARD: "Product Dashboard",
  PRODUCTS_PRODUCT_AUTO_GENRATE_SKU: "Auto Genrate SKU",
  PRODUCTS_STORE: "Store",
  PRODUCTS_TITLE: "Title",
  PRODUCTS_DESCRIPTION: "Description",
  PRODUCTS_CATEGORY: "Category",
  PRODUCTS_WEIGHT: "Weight",
  PRODUCTS_SALE_PRICE: "Sale Price",
  PRODUCTS_FEATURE_IMAGE: "Feature Image",
  PRODUCTS_INVENTORY: "Inventory",
  PRODUCTS_TRACK_INVENTORY: "Track Inventory",
  PRODUCTS_AUTO_GENERATE_SKU: "Auto Generate SKU",
  PRODUCTS_DUBAI: "Dubai",
  PRODUCTS_TEST: "Test",
  PRODUCTS_HII: "Hii",
  PRODUCTS_HOW: "How",
  PRODUCTS_STAGE: "Stage (Default)",
  PRODUCTS_RTERTERTGETGEE: "Rtertertgetgee",
  PRODUCTS_QUANTITY: "Quantity",
  PRODUCTS_LOW_QUANTITY_AMOUNT: "Low Quantity Amount",
  PRODUCTS_PRODUCT_HAS_OPTIONS: "This product has options.",
  PRODUCTS_CREATE_PRODUCT: "Create Product",
  PRODUCTS_START_DATE: "Start Date",
  PRODUCTS_END_DATE: "End Date",
  PRODUCTS_SELECT_PLEASE: "Select Please",
  PRODUCTS_CLEAR_FILTER: "Clear Filter",
  PRODUCT_FILTER: "Filter",
};
export const productsArabic = {
  ...inventoryArabic,
  ...lowInventoryArabic,
  ...inventorySaleArabic,
  ...SaleChannelProductArabic,
  ...ProductStationArabic,
  PRODUCTS_TEXT: "منتجات",
  PRODUCTS_TEXT_S: "منتجات",
  PRODUCT_ALL: "الجميع",
  PRODUCT_ACTIVE: "نشيط",
  PRODUCT_IN_ACTIVE: "غير نشط",
  PRODUCTS_ADD_PRODUCTS: "إضافة منتجات",
  PRODUCTS_SKU: "إس كيو يو",
  PRODUCTS_CATEGORY_NAME: "اسم الفئة",
  PRODUCTS_STORE_NAME: "اسم المتجر",
  PRODUCTS_QTY_AVAILABLE: "الكمية المتاحة",
  PRODUCTS_WEIGHT: "الوزن",
  PRODUCTS_PURCHASE_PRICE: "سعر الشراء",
  PRODUCTS_SALE_PRICE: "سعر البيع",
  PRODUCTS_STATUS: "الحالة",
  PRODUCTS_ACTION: "الإجراء",
  PRODUCTS_PRODUCT_DETAIL: "تفاصيل المنتج",
  PRODUCTS_STORE: "المتجر",
  PRODUCTS_TITLE: "العنوان",
  PRODUCTS_DESCRIPTION: "الوصف",
  PRODUCTS_CATEGORY: "الفئة",
  PRODUCTS_WEIGHT: "الوزن",
  PRODUCTS_SALE_PRICE: "سعر البيع",
  PRODUCTS_PURCHASE_PRICE: "سعر الشراء",
  PRODUCTS_FEATURE_IMAGE: "الصورة المميزة",
  PRODUCTS_INVENTORY: "المخزون",
  PRODUCTS_TRACK_INVENTORY: "تتبع المخزون",
  PRODUCTS_AUTO_GENERATE_SKU: "توليد إس كيو يو تلقائيًا",
  PRODUCTS_DUBAI: "دبي",
  PRODUCTS_TEST: "اختبار",
  PRODUCTS_HII: "مرحبًا",
  PRODUCTS_HOW: "كيف",
  PRODUCTS_STAGE: "المرحلة (افتراضي)",
  PRODUCTS_RTERTERTGETGEE: "رترترتكجي",
  PRODUCTS_QUANTITY: "الكمية",
  PRODUCTS_LOW_QUANTITY_AMOUNT: "كمية منخفضة",
  PRODUCTS_PRODUCT_HAS_OPTIONS: "هذا المنتج له خيارات.",
  PRODUCTS_CREATE_PRODUCT: "إنشاء منتج",
  PRODUCTS_START_DATE: "تاريخ البدء",
  PRODUCTS_END_DATE: "تاريخ الانتهاء",
  PRODUCTS_SELECT_PLEASE: "يرجى التحديد",
  PRODUCTS_CLEAR_FILTER: "مسح الفلتر",
  PRODUCT_FILTER: "منقي",
  PRODUCTS_PRODUCT_DASHBOARD: "لوحة معلومات المنتج",
  PRODUCTS_PRODUCT_AUTO_GENRATE_SKU: "توليد SKU تلقائيًا",
};
export const productsChinese = {
  ...inventoryChines,
  ...lowInventoryChines,
  ...inventorySaleChines,
  ...SaleChannelProductChines,
  ...ProductStationChines,
  PRODUCTS_TEXT: "产品",
  PRODUCTS_TEXT_S: "产品",
  PRODUCT_ALL: "全部",
  PRODUCT_ACTIVE: "积极的",
  PRODUCT_IN_ACTIVE: "活跃中",
  PRODUCTS_ADD_PRODUCTS: "添加产品",
  PRODUCTS_SKU: "SKU(库存单位)",
  PRODUCTS_CATEGORY_NAME: "类别名称",
  PRODUCTS_STORE_NAME: "店铺名称",
  PRODUCTS_QTY_AVAILABLE: "可用数量",
  PRODUCTS_WEIGHT: "重量",
  PRODUCTS_PURCHASE_PRICE: "采购价格",
  PRODUCTS_SALE_PRICE: "销售价格",
  PRODUCTS_STATUS: "状态",
  PRODUCTS_ACTION: "操作",
  PRODUCTS_PRODUCT_DETAIL: "产品详情",
  PRODUCTS_PRODUCT_DASHBOARD: "产品仪表板",
  PRODUCTS_PRODUCT_AUTO_GENRATE_SKU: "自动生成 SKU ",
  PRODUCTS_STORE: "店铺",
  PRODUCTS_TITLE: "标题",
  PRODUCTS_DESCRIPTION: "描述",
  PRODUCTS_CATEGORY: "类别",
  PRODUCTS_WEIGHT: "重量",
  PRODUCTS_SALE_PRICE: "销售价格",
  PRODUCTS_PURCHASE_PRICE: "采购价格",
  PRODUCTS_FEATURE_IMAGE: "特色图像",
  PRODUCTS_INVENTORY: "库存",
  PRODUCTS_TRACK_INVENTORY: "跟踪库存",
  PRODUCTS_AUTO_GENERATE_SKU: "自动生成SKU",
  PRODUCTS_DUBAI: "迪拜",
  PRODUCTS_TEST: "测试",
  PRODUCTS_HII: "嗨",
  PRODUCTS_HOW: "如何",
  PRODUCTS_STAGE: "阶段（默认）",
  PRODUCTS_RTERTERTGETGEE: "瑞特特特哥",
  PRODUCTS_QUANTITY: "数量",
  PRODUCTS_LOW_QUANTITY_AMOUNT: "低库存数量",
  PRODUCTS_PRODUCT_HAS_OPTIONS: "此产品有选项。",
  PRODUCTS_CREATE_PRODUCT: "创建产品",
  PRODUCTS_START_DATE: "开始日期",
  PRODUCTS_END_DATE: "结束日期",
  PRODUCTS_SELECT_PLEASE: "请选择",
  PRODUCTS_CLEAR_FILTER: "清除筛选",
  PRODUCT_FILTER: "筛选",
};
export const productsUrdu = {
  ...inventoryUrdu,
  ...lowInventoryUrdu,
  ...inventorySaleUrdu,
  ...SaleChannelProductUrdu,
  ...ProductStationUrdu,
  PRODUCTS_TEXT: "پروڈکٹس",
  PRODUCTS_TEXT_S: "پروڈکٹ(ز)",
  PRODUCT_ALL: "تمام",
  PRODUCT_ACTIVE: "فعال",
  PRODUCT_IN_ACTIVE: "غیرفعال",
  PRODUCTS_ADD_PRODUCTS: "پروڈکٹس شامل کریں",
  PRODUCTS_SKU: "ایس کے یو",
  PRODUCTS_CATEGORY_NAME: "زمرے کا نام",
  PRODUCTS_STORE_NAME: "اسٹور کا نام",
  PRODUCTS_QTY_AVAILABLE: "دستیاب مقدار",
  PRODUCTS_WEIGHT: "وزن",
  PRODUCTS_PURCHASE_PRICE: "خریداری قیمت",
  PRODUCTS_SALE_PRICE: "فروخت قیمت",
  PRODUCTS_STATUS: "اسٹیٹس",
  PRODUCTS_ACTION: "عمل",
  PRODUCTS_PRODUCT_DETAIL: "پروڈکٹ کی تفصیل",
  PRODUCTS_PRODUCT_DASHBOARD: "پروڈکٹ ڈیش بورڈ",
  PRODUCTS_PRODUCT_AUTO_GENRATE_SKU: "خودکار طور پر ایس کے یو بنائیں",
  PRODUCTS_STORE: "اسٹور",
  PRODUCTS_TITLE: "عنوان",
  PRODUCTS_DESCRIPTION: "تفصیل",
  PRODUCTS_CATEGORY: "زمرہ",
  PRODUCTS_WEIGHT: "وزن",
  PRODUCTS_SALE_PRICE: "فروخت قیمت",
  PRODUCTS_FEATURE_IMAGE: "نمایاں تصویر",
  PRODUCTS_INVENTORY: "انوینٹری",
  PRODUCTS_TRACK_INVENTORY: "انوینٹری کا پتہ لگائیں",
  PRODUCTS_AUTO_GENERATE_SKU: "خودکار ایس کے یو بنائیں",
  PRODUCTS_DUBAI: "دبئی",
  PRODUCTS_TEST: "ٹیسٹ",
  PRODUCTS_HII: "ہیلو",
  PRODUCTS_HOW: "کیسے",
  PRODUCTS_STAGE: "اسٹیج (ڈیفالٹ)",
  PRODUCTS_RTERTERTGETGEE: "آر ٹی ای آر ٹی ای آر ٹی جی ای ٹی جی ای ای",
  PRODUCTS_QUANTITY: "مقدار",
  PRODUCTS_LOW_QUANTITY_AMOUNT: "کم مقدار کی حد",
  PRODUCTS_PRODUCT_HAS_OPTIONS: "اس پروڈکٹ میں اختیارات موجود ہیں۔",
  PRODUCTS_CREATE_PRODUCT: "پروڈکٹ بنائیں",
  PRODUCTS_START_DATE: "شروع ہونے کی تاریخ",
  PRODUCTS_END_DATE: "اختتام کی تاریخ",
  PRODUCTS_SELECT_PLEASE: "منتخب کریں براہ کرم",
  PRODUCTS_CLEAR_FILTER: "فلٹر صاف کریں",
  PRODUCT_FILTER: "فلٹر",
};
