version: '3'

services:
  seq:
    image: datalust/seq:latest
    ports:
      - 5341:80
    env_file:
      - seq.env
    volumes:
      - myseq:/data
    environment:
      - ACCEPT_EULA=Y
  prometheus:
    image: ubuntu/prometheus
    container_name: dev_prometheus
    ports:
      - "30090:9090"
    environment:
      - TZ=UTC
    volumes:
      - ./prom/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    container_name: dev_grafana
    ports:
      - "30091:3000"
    volumes:
      - ./grafana-data/data:/var/lib/grafana

volumes:
  myseq: